// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CatchPokemonResponse.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace PokemonGo.RocketAPI.GeneratedCode {

  /// <summary>Holder for reflection information generated from CatchPokemonResponse.proto</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class CatchPokemonResponseReflection {

    #region Descriptor
    /// <summary>File descriptor for CatchPokemonResponse.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CatchPokemonResponseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChpDYXRjaFBva2Vtb25SZXNwb25zZS5wcm90bxIhUG9rZW1vbkdvLlJvY2tl",
            "dEFQSS5HZW5lcmF0ZWRDb2RlIqsmChRDYXRjaFBva2Vtb25SZXNwb25zZRIQ",
            "Cgh1bmtub3duMRgBIAEoBRIQCgh1bmtub3duMhgCIAEoAxIPCgdhcGlfdXJs",
            "GAMgASgJElIKCHVua25vd242GAYgASgLMkAuUG9rZW1vbkdvLlJvY2tldEFQ",
            "SS5HZW5lcmF0ZWRDb2RlLkNhdGNoUG9rZW1vblJlc3BvbnNlLlVua25vd242",
            "ElIKCHVua25vd243GAcgASgLMkAuUG9rZW1vbkdvLlJvY2tldEFQSS5HZW5l",
            "cmF0ZWRDb2RlLkNhdGNoUG9rZW1vblJlc3BvbnNlLlVua25vd243ElAKB3Bh",
            "eWxvYWQYZCADKAsyPy5Qb2tlbW9uR28uUm9ja2V0QVBJLkdlbmVyYXRlZENv",
            "ZGUuQ2F0Y2hQb2tlbW9uUmVzcG9uc2UuUGF5bG9hZBIUCgxlcnJvck1lc3Nh",
            "Z2UYZSABKAkalwEKCFVua25vd242EhAKCHVua25vd24xGAEgASgFElsKCHVu",
            "a25vd24yGAIgASgLMkkuUG9rZW1vbkdvLlJvY2tldEFQSS5HZW5lcmF0ZWRD",
            "b2RlLkNhdGNoUG9rZW1vblJlc3BvbnNlLlVua25vd242LlVua25vd24yGhwK",
            "CFVua25vd24yEhAKCHVua25vd24xGAEgASgMGkMKCFVua25vd243EhEKCXVu",
            "a25vd243MRgBIAEoDBIRCgl1bmtub3duNzIYAiABKAMSEQoJdW5rbm93bjcz",
            "GAMgASgMGp0BCgdQYXlsb2FkEg4KBlN0YXR1cxgBIAEoBRITCgtNaXNzUGVy",
            "Y2VudBgCIAEoBhJdChFDYXB0dXJlZFBva2Vtb25JZBgDIAEoDjJCLlBva2Vt",
            "b25Hby5Sb2NrZXRBUEkuR2VuZXJhdGVkQ29kZS5DYXRjaFBva2Vtb25SZXNw",
            "b25zZS5Qb2tlbW9uSWRzEg4KBlNjb3JlcxgEIAEoBSLOIAoKUG9rZW1vbklk",
            "cxIRCg1QT0tFTU9OX1VOU0VUEAASGwoXVjAwMDFfUE9LRU1PTl9CVUxCQVNB",
            "VVIQARIZChVWMDAwMl9QT0tFTU9OX0lWWVNBVVIQAhIaChZWMDAwM19QT0tF",
            "TU9OX1ZFTlVTQVVSEAMSHAoYVjAwMDRfUE9LRU1PTl9DSEFSTUFOREVSEAQS",
            "HAoYVjAwMDVfUE9LRU1PTl9DSEFSTUVMRU9OEAUSGwoXVjAwMDZfUE9LRU1P",
            "Tl9DSEFSSVpBUkQQBhIaChZWMDAwN19QT0tFTU9OX1NRVUlSVExFEAcSGwoX",
            "VjAwMDhfUE9LRU1PTl9XQVJUT1JUTEUQCBIbChdWMDAwOV9QT0tFTU9OX0JM",
            "QVNUT0lTRRAJEhoKFlYwMDEwX1BPS0VNT05fQ0FURVJQSUUQChIZChVWMDAx",
            "MV9QT0tFTU9OX01FVEFQT0QQCxIcChhWMDAxMl9QT0tFTU9OX0JVVFRFUkZS",
            "RUUQDBIYChRWMDAxM19QT0tFTU9OX1dFRURMRRANEhgKFFYwMDE0X1BPS0VN",
            "T05fS0FLVU5BEA4SGgoWVjAwMTVfUE9LRU1PTl9CRUVEUklMTBAPEhgKFFYw",
            "MDE2X1BPS0VNT05fUElER0VZEBASGwoXVjAwMTdfUE9LRU1PTl9QSURHRU9U",
            "VE8QERIZChVWMDAxOF9QT0tFTU9OX1BJREdFT1QQEhIZChVWMDAxOV9QT0tF",
            "TU9OX1JBVFRBVEEQExIaChZWMDAyMF9QT0tFTU9OX1JBVElDQVRFEBQSGQoV",
            "VjAwMjFfUE9LRU1PTl9TUEVBUk9XEBUSGAoUVjAwMjJfUE9LRU1PTl9GRUFS",
            "T1cQFhIXChNWMDAyM19QT0tFTU9OX0VLQU5TEBcSFwoTVjAwMjRfUE9LRU1P",
            "Tl9BUkJPSxAYEhkKFVYwMDI1X1BPS0VNT05fUElLQUNIVRAZEhgKFFYwMDI2",
            "X1BPS0VNT05fUkFJQ0hVEBoSGwoXVjAwMjdfUE9LRU1PTl9TQU5EU0hSRVcQ",
            "GxIbChdWMDAyOF9QT0tFTU9OX1NBTkRTTEFTSBAcEhkKFVYwMDI5X1BPS0VN",
            "T05fTklET1JBThAdEhoKFlYwMDMwX1BPS0VNT05fTklET1JJTkEQHhIbChdW",
            "MDAzMV9QT0tFTU9OX05JRE9RVUVFThAfEhkKFVYwMDMyX1BPS0VNT05fTklE",
            "T1JBThAgEhoKFlYwMDMzX1BPS0VNT05fTklET1JJTk8QIRIaChZWMDAzNF9Q",
            "T0tFTU9OX05JRE9LSU5HECISGgoWVjAwMzVfUE9LRU1PTl9DTEVGQUlSWRAj",
            "EhoKFlYwMDM2X1BPS0VNT05fQ0xFRkFCTEUQJBIYChRWMDAzN19QT0tFTU9O",
            "X1ZVTFBJWBAlEhsKF1YwMDM4X1BPS0VNT05fTklORVRBTEVTECYSHAoYVjAw",
            "MzlfUE9LRU1PTl9KSUdHTFlQVUZGECcSHAoYVjAwNDBfUE9LRU1PTl9XSUdH",
            "TFlUVUZGECgSFwoTVjAwNDFfUE9LRU1PTl9aVUJBVBApEhgKFFYwMDQyX1BP",
            "S0VNT05fR09MQkFUECoSGAoUVjAwNDNfUE9LRU1PTl9PRERJU0gQKxIXChNW",
            "MDA0NF9QT0tFTU9OX0dMT09NECwSGwoXVjAwNDVfUE9LRU1PTl9WSUxFUExV",
            "TUUQLRIXChNWMDA0Nl9QT0tFTU9OX1BBUkFTEC4SGgoWVjAwNDdfUE9LRU1P",
            "Tl9QQVJBU0VDVBAvEhkKFVYwMDQ4X1BPS0VNT05fVkVOT05BVBAwEhoKFlYw",
            "MDQ5X1BPS0VNT05fVkVOT01PVEgQMRIZChVWMDA1MF9QT0tFTU9OX0RJR0xF",
            "VFQQMhIZChVWMDA1MV9QT0tFTU9OX0RVR1RSSU8QMxIYChRWMDA1Ml9QT0tF",
            "TU9OX01FT1dUSBA0EhkKFVYwMDUzX1BPS0VNT05fUEVSU0lBThA1EhkKFVYw",
            "MDU0X1BPS0VNT05fUFNZRFVDSxA2EhkKFVYwMDU1X1BPS0VNT05fR09MRFVD",
            "SxA3EhgKFFYwMDU2X1BPS0VNT05fTUFOS0VZEDgSGgoWVjAwNTdfUE9LRU1P",
            "Tl9QUklNRUFQRRA5EhsKF1YwMDU4X1BPS0VNT05fR1JPV0xJVEhFEDoSGgoW",
            "VjAwNTlfUE9LRU1PTl9BUkNBTklORRA7EhkKFVYwMDYwX1BPS0VNT05fUE9M",
            "SVdBRxA8EhsKF1YwMDYxX1BPS0VNT05fUE9MSVdISVJMED0SGwoXVjAwNjJf",
            "UE9LRU1PTl9QT0xJV1JBVEgQPhIWChJWMDA2M19QT0tFTU9OX0FCUkEQPxIZ",
            "ChVWMDA2NF9QT0tFTU9OX0tBREFCUkEQQBIaChZWMDA2NV9QT0tFTU9OX0FM",
            "QUtBWkFNEEESGAoUVjAwNjZfUE9LRU1PTl9NQUNIT1AQQhIZChVWMDA2N19Q",
            "T0tFTU9OX01BQ0hPS0UQQxIZChVWMDA2OF9QT0tFTU9OX01BQ0hBTVAQRBIc",
            "ChhWMDA2OV9QT0tFTU9OX0JFTExTUFJPVVQQRRIcChhWMDA3MF9QT0tFTU9O",
            "X1dFRVBJTkJFTEwQRhIcChhWMDA3MV9QT0tFTU9OX1ZJQ1RSRUVCRUwQRxIb",
            "ChdWMDA3Ml9QT0tFTU9OX1RFTlRBQ09PTBBIEhwKGFYwMDczX1BPS0VNT05f",
            "VEVOVEFDUlVFTBBJEhkKFVYwMDc0X1BPS0VNT05fR0VPRFVERRBKEhoKFlYw",
            "MDc1X1BPS0VNT05fR1JBVkVMRVIQSxIXChNWMDA3Nl9QT0tFTU9OX0dPTEVN",
            "EEwSGAoUVjAwNzdfUE9LRU1PTl9QT05ZVEEQTRIaChZWMDA3OF9QT0tFTU9O",
            "X1JBUElEQVNIEE4SGgoWVjAwNzlfUE9LRU1PTl9TTE9XUE9LRRBPEhkKFVYw",
            "MDgwX1BPS0VNT05fU0xPV0JSTxBQEhsKF1YwMDgxX1BPS0VNT05fTUFHTkVN",
            "SVRFEFESGgoWVjAwODJfUE9LRU1PTl9NQUdORVRPThBSEhsKF1YwMDgzX1BP",
            "S0VNT05fRkFSRkVUQ0hEEFMSFwoTVjAwODRfUE9LRU1PTl9ET0RVTxBUEhgK",
            "FFYwMDg1X1BPS0VNT05fRE9EUklPEFUSFgoSVjAwODZfUE9LRU1PTl9TRUVM",
            "EFYSGQoVVjAwODdfUE9LRU1PTl9ERVdHT05HEFcSGAoUVjAwODhfUE9LRU1P",
            "Tl9HUklNRVIQWBIVChFWMDA4OV9QT0tFTU9OX01VSxBZEhoKFlYwMDkwX1BP",
            "S0VNT05fU0hFTExERVIQWhIaChZWMDA5MV9QT0tFTU9OX0NMT1lTVEVSEFsS",
            "GAoUVjAwOTJfUE9LRU1PTl9HQVNUTFkQXBIZChVWMDA5M19QT0tFTU9OX0hB",
            "VU5URVIQXRIYChRWMDA5NF9QT0tFTU9OX0dFTkdBUhBeEhYKElYwMDk1X1BP",
            "S0VNT05fT05JWBBfEhkKFVYwMDk2X1BPS0VNT05fRFJPV1pFRRBgEhcKE1Yw",
            "MDk3X1BPS0VNT05fSFlQTk8QYRIYChRWMDA5OF9QT0tFTU9OX0tSQUJCWRBi",
            "EhkKFVYwMDk5X1BPS0VNT05fS0lOR0xFUhBjEhkKFVYwMTAwX1BPS0VNT05f",
            "Vk9MVE9SQhBkEhsKF1YwMTAxX1BPS0VNT05fRUxFQ1RST0RFEGUSGwoXVjAx",
            "MDJfUE9LRU1PTl9FWEVHR0NVVEUQZhIbChdWMDEwM19QT0tFTU9OX0VYRUdH",
            "VVRPUhBnEhgKFFYwMTA0X1BPS0VNT05fQ1VCT05FEGgSGQoVVjAxMDVfUE9L",
            "RU1PTl9NQVJPV0FLEGkSGwoXVjAxMDZfUE9LRU1PTl9ISVRNT05MRUUQahIc",
            "ChhWMDEwN19QT0tFTU9OX0hJVE1PTkNIQU4QaxIbChdWMDEwOF9QT0tFTU9O",
            "X0xJQ0tJVFVORxBsEhkKFVYwMTA5X1BPS0VNT05fS09GRklORxBtEhkKFVYw",
            "MTEwX1BPS0VNT05fV0VFWklORxBuEhkKFVYwMTExX1BPS0VNT05fUkhZSE9S",
            "ThBvEhgKFFYwMTEyX1BPS0VNT05fUkhZRE9OEHASGQoVVjAxMTNfUE9LRU1P",
            "Tl9DSEFOU0VZEHESGQoVVjAxMTRfUE9LRU1PTl9UQU5HRUxBEHISHAoYVjAx",
            "MTVfUE9LRU1PTl9LQU5HQVNLSEFOEHMSGAoUVjAxMTZfUE9LRU1PTl9IT1JT",
            "RUEQdBIYChRWMDExN19QT0tFTU9OX1NFQURSQRB1EhkKFVYwMTE4X1BPS0VN",
            "T05fR09MREVFThB2EhkKFVYwMTE5X1BPS0VNT05fU0VBS0lORxB3EhgKFFYw",
            "MTIwX1BPS0VNT05fU1RBUllVEHgSGQoVVjAxMjFfUE9LRU1PTl9TVEFSTUlF",
            "EHkSGQoVVjAxMjJfUE9LRU1PTl9NUl9NSU1FEHoSGQoVVjAxMjNfUE9LRU1P",
            "Tl9TQ1lUSEVSEHsSFgoSVjAxMjRfUE9LRU1PTl9KWU5YEHwSHAoYVjAxMjVf",
            "UE9LRU1PTl9FTEVDVEFCVVpaEH0SGAoUVjAxMjZfUE9LRU1PTl9NQUdNQVIQ",
            "fhIYChRWMDEyN19QT0tFTU9OX1BJTlNJUhB/EhkKFFYwMTI4X1BPS0VNT05f",
            "VEFVUk9TEIABEhsKFlYwMTI5X1BPS0VNT05fTUFHSUtBUlAQgQESGwoWVjAx",
            "MzBfUE9LRU1PTl9HWUFSQURPUxCCARIZChRWMDEzMV9QT0tFTU9OX0xBUFJB",
            "UxCDARIYChNWMDEzMl9QT0tFTU9OX0RJVFRPEIQBEhgKE1YwMTMzX1BPS0VN",
            "T05fRUVWRUUQhQESGwoWVjAxMzRfUE9LRU1PTl9WQVBPUkVPThCGARIaChVW",
            "MDEzNV9QT0tFTU9OX0pPTFRFT04QhwESGgoVVjAxMzZfUE9LRU1PTl9GTEFS",
            "RU9OEIgBEhoKFVYwMTM3X1BPS0VNT05fUE9SWUdPThCJARIaChVWMDEzOF9Q",
            "T0tFTU9OX09NQU5ZVEUQigESGgoVVjAxMzlfUE9LRU1PTl9PTUFTVEFSEIsB",
            "EhkKFFYwMTQwX1BPS0VNT05fS0FCVVRPEIwBEhsKFlYwMTQxX1BPS0VNT05f",
            "S0FCVVRPUFMQjQESHQoYVjAxNDJfUE9LRU1PTl9BRVJPREFDVFlMEI4BEhoK",
            "FVYwMTQzX1BPS0VNT05fU05PUkxBWBCPARIbChZWMDE0NF9QT0tFTU9OX0FS",
            "VElDVU5PEJABEhkKFFYwMTQ1X1BPS0VNT05fWkFQRE9TEJEBEhoKFVYwMTQ2",
            "X1BPS0VNT05fTU9MVFJFUxCSARIaChVWMDE0N19QT0tFTU9OX0RSQVRJTkkQ",
            "kwESHAoXVjAxNDhfUE9LRU1PTl9EUkFHT05BSVIQlAESHAoXVjAxNDlfUE9L",
            "RU1PTl9EUkFHT05JVEUQlQESGQoUVjAxNTBfUE9LRU1PTl9NRVdUV08QlgES",
            "FgoRVjAxNTFfUE9LRU1PTl9NRVcQlwFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::PokemonGo.RocketAPI.GeneratedCode.CatchPokemonResponse), global::PokemonGo.RocketAPI.GeneratedCode.CatchPokemonResponse.Parser, new[]{ "Unknown1", "Unknown2", "ApiUrl", "Unknown6", "Unknown7", "Payload", "ErrorMessage" }, null, new[]{ typeof(global::PokemonGo.RocketAPI.GeneratedCode.CatchPokemonResponse.Types.PokemonIds) }, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::PokemonGo.RocketAPI.GeneratedCode.CatchPokemonResponse.Types.Unknown6), global::PokemonGo.RocketAPI.GeneratedCode.CatchPokemonResponse.Types.Unknown6.Parser, new[]{ "Unknown1", "Unknown2" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::PokemonGo.RocketAPI.GeneratedCode.CatchPokemonResponse.Types.Unknown6.Types.Unknown2), global::PokemonGo.RocketAPI.GeneratedCode.CatchPokemonResponse.Types.Unknown6.Types.Unknown2.Parser, new[]{ "Unknown1" }, null, null, null)}),
            new pbr::GeneratedClrTypeInfo(typeof(global::PokemonGo.RocketAPI.GeneratedCode.CatchPokemonResponse.Types.Unknown7), global::PokemonGo.RocketAPI.GeneratedCode.CatchPokemonResponse.Types.Unknown7.Parser, new[]{ "Unknown71", "Unknown72", "Unknown73" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::PokemonGo.RocketAPI.GeneratedCode.CatchPokemonResponse.Types.Payload), global::PokemonGo.RocketAPI.GeneratedCode.CatchPokemonResponse.Types.Payload.Parser, new[]{ "Status", "MissPercent", "CapturedPokemonId", "Scores" }, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class CatchPokemonResponse : pb::IMessage<CatchPokemonResponse> {
    private static readonly pb::MessageParser<CatchPokemonResponse> _parser = new pb::MessageParser<CatchPokemonResponse>(() => new CatchPokemonResponse());
    public static pb::MessageParser<CatchPokemonResponse> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::PokemonGo.RocketAPI.GeneratedCode.CatchPokemonResponseReflection.Descriptor.MessageTypes[0]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public CatchPokemonResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    public CatchPokemonResponse(CatchPokemonResponse other) : this() {
      unknown1_ = other.unknown1_;
      unknown2_ = other.unknown2_;
      apiUrl_ = other.apiUrl_;
      Unknown6 = other.unknown6_ != null ? other.Unknown6.Clone() : null;
      Unknown7 = other.unknown7_ != null ? other.Unknown7.Clone() : null;
      payload_ = other.payload_.Clone();
      errorMessage_ = other.errorMessage_;
    }

    public CatchPokemonResponse Clone() {
      return new CatchPokemonResponse(this);
    }

    /// <summary>Field number for the "unknown1" field.</summary>
    public const int Unknown1FieldNumber = 1;
    private int unknown1_;
    public int Unknown1 {
      get { return unknown1_; }
      set {
        unknown1_ = value;
      }
    }

    /// <summary>Field number for the "unknown2" field.</summary>
    public const int Unknown2FieldNumber = 2;
    private long unknown2_;
    public long Unknown2 {
      get { return unknown2_; }
      set {
        unknown2_ = value;
      }
    }

    /// <summary>Field number for the "api_url" field.</summary>
    public const int ApiUrlFieldNumber = 3;
    private string apiUrl_ = "";
    public string ApiUrl {
      get { return apiUrl_; }
      set {
        apiUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "unknown6" field.</summary>
    public const int Unknown6FieldNumber = 6;
    private global::PokemonGo.RocketAPI.GeneratedCode.CatchPokemonResponse.Types.Unknown6 unknown6_;
    public global::PokemonGo.RocketAPI.GeneratedCode.CatchPokemonResponse.Types.Unknown6 Unknown6 {
      get { return unknown6_; }
      set {
        unknown6_ = value;
      }
    }

    /// <summary>Field number for the "unknown7" field.</summary>
    public const int Unknown7FieldNumber = 7;
    private global::PokemonGo.RocketAPI.GeneratedCode.CatchPokemonResponse.Types.Unknown7 unknown7_;
    public global::PokemonGo.RocketAPI.GeneratedCode.CatchPokemonResponse.Types.Unknown7 Unknown7 {
      get { return unknown7_; }
      set {
        unknown7_ = value;
      }
    }

    /// <summary>Field number for the "payload" field.</summary>
    public const int PayloadFieldNumber = 100;
    private static readonly pb::FieldCodec<global::PokemonGo.RocketAPI.GeneratedCode.CatchPokemonResponse.Types.Payload> _repeated_payload_codec
        = pb::FieldCodec.ForMessage(802, global::PokemonGo.RocketAPI.GeneratedCode.CatchPokemonResponse.Types.Payload.Parser);
    private readonly pbc::RepeatedField<global::PokemonGo.RocketAPI.GeneratedCode.CatchPokemonResponse.Types.Payload> payload_ = new pbc::RepeatedField<global::PokemonGo.RocketAPI.GeneratedCode.CatchPokemonResponse.Types.Payload>();
    public pbc::RepeatedField<global::PokemonGo.RocketAPI.GeneratedCode.CatchPokemonResponse.Types.Payload> Payload {
      get { return payload_; }
    }

    /// <summary>Field number for the "errorMessage" field.</summary>
    public const int ErrorMessageFieldNumber = 101;
    private string errorMessage_ = "";
    /// <summary>
    /// Should be moved to an error-proto file if error is always 101 field
    /// </summary>
    public string ErrorMessage {
      get { return errorMessage_; }
      set {
        errorMessage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public override bool Equals(object other) {
      return Equals(other as CatchPokemonResponse);
    }

    public bool Equals(CatchPokemonResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Unknown1 != other.Unknown1) return false;
      if (Unknown2 != other.Unknown2) return false;
      if (ApiUrl != other.ApiUrl) return false;
      if (!object.Equals(Unknown6, other.Unknown6)) return false;
      if (!object.Equals(Unknown7, other.Unknown7)) return false;
      if(!payload_.Equals(other.payload_)) return false;
      if (ErrorMessage != other.ErrorMessage) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      if (Unknown1 != 0) hash ^= Unknown1.GetHashCode();
      if (Unknown2 != 0L) hash ^= Unknown2.GetHashCode();
      if (ApiUrl.Length != 0) hash ^= ApiUrl.GetHashCode();
      if (unknown6_ != null) hash ^= Unknown6.GetHashCode();
      if (unknown7_ != null) hash ^= Unknown7.GetHashCode();
      hash ^= payload_.GetHashCode();
      if (ErrorMessage.Length != 0) hash ^= ErrorMessage.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (Unknown1 != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Unknown1);
      }
      if (Unknown2 != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Unknown2);
      }
      if (ApiUrl.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ApiUrl);
      }
      if (unknown6_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Unknown6);
      }
      if (unknown7_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(Unknown7);
      }
      payload_.WriteTo(output, _repeated_payload_codec);
      if (ErrorMessage.Length != 0) {
        output.WriteRawTag(170, 6);
        output.WriteString(ErrorMessage);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (Unknown1 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Unknown1);
      }
      if (Unknown2 != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Unknown2);
      }
      if (ApiUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ApiUrl);
      }
      if (unknown6_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Unknown6);
      }
      if (unknown7_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Unknown7);
      }
      size += payload_.CalculateSize(_repeated_payload_codec);
      if (ErrorMessage.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(ErrorMessage);
      }
      return size;
    }

    public void MergeFrom(CatchPokemonResponse other) {
      if (other == null) {
        return;
      }
      if (other.Unknown1 != 0) {
        Unknown1 = other.Unknown1;
      }
      if (other.Unknown2 != 0L) {
        Unknown2 = other.Unknown2;
      }
      if (other.ApiUrl.Length != 0) {
        ApiUrl = other.ApiUrl;
      }
      if (other.unknown6_ != null) {
        if (unknown6_ == null) {
          unknown6_ = new global::PokemonGo.RocketAPI.GeneratedCode.CatchPokemonResponse.Types.Unknown6();
        }
        Unknown6.MergeFrom(other.Unknown6);
      }
      if (other.unknown7_ != null) {
        if (unknown7_ == null) {
          unknown7_ = new global::PokemonGo.RocketAPI.GeneratedCode.CatchPokemonResponse.Types.Unknown7();
        }
        Unknown7.MergeFrom(other.Unknown7);
      }
      payload_.Add(other.payload_);
      if (other.ErrorMessage.Length != 0) {
        ErrorMessage = other.ErrorMessage;
      }
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Unknown1 = input.ReadInt32();
            break;
          }
          case 16: {
            Unknown2 = input.ReadInt64();
            break;
          }
          case 26: {
            ApiUrl = input.ReadString();
            break;
          }
          case 50: {
            if (unknown6_ == null) {
              unknown6_ = new global::PokemonGo.RocketAPI.GeneratedCode.CatchPokemonResponse.Types.Unknown6();
            }
            input.ReadMessage(unknown6_);
            break;
          }
          case 58: {
            if (unknown7_ == null) {
              unknown7_ = new global::PokemonGo.RocketAPI.GeneratedCode.CatchPokemonResponse.Types.Unknown7();
            }
            input.ReadMessage(unknown7_);
            break;
          }
          case 802: {
            payload_.AddEntriesFrom(input, _repeated_payload_codec);
            break;
          }
          case 810: {
            ErrorMessage = input.ReadString();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the CatchPokemonResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public static partial class Types {
      public enum PokemonIds {
        [pbr::OriginalName("POKEMON_UNSET")] PokemonUnset = 0,
        [pbr::OriginalName("V0001_POKEMON_BULBASAUR")] V0001PokemonBulbasaur = 1,
        [pbr::OriginalName("V0002_POKEMON_IVYSAUR")] V0002PokemonIvysaur = 2,
        [pbr::OriginalName("V0003_POKEMON_VENUSAUR")] V0003PokemonVenusaur = 3,
        [pbr::OriginalName("V0004_POKEMON_CHARMANDER")] V0004PokemonCharmander = 4,
        [pbr::OriginalName("V0005_POKEMON_CHARMELEON")] V0005PokemonCharmeleon = 5,
        [pbr::OriginalName("V0006_POKEMON_CHARIZARD")] V0006PokemonCharizard = 6,
        [pbr::OriginalName("V0007_POKEMON_SQUIRTLE")] V0007PokemonSquirtle = 7,
        [pbr::OriginalName("V0008_POKEMON_WARTORTLE")] V0008PokemonWartortle = 8,
        [pbr::OriginalName("V0009_POKEMON_BLASTOISE")] V0009PokemonBlastoise = 9,
        [pbr::OriginalName("V0010_POKEMON_CATERPIE")] V0010PokemonCaterpie = 10,
        [pbr::OriginalName("V0011_POKEMON_METAPOD")] V0011PokemonMetapod = 11,
        [pbr::OriginalName("V0012_POKEMON_BUTTERFREE")] V0012PokemonButterfree = 12,
        [pbr::OriginalName("V0013_POKEMON_WEEDLE")] V0013PokemonWeedle = 13,
        [pbr::OriginalName("V0014_POKEMON_KAKUNA")] V0014PokemonKakuna = 14,
        [pbr::OriginalName("V0015_POKEMON_BEEDRILL")] V0015PokemonBeedrill = 15,
        [pbr::OriginalName("V0016_POKEMON_PIDGEY")] V0016PokemonPidgey = 16,
        [pbr::OriginalName("V0017_POKEMON_PIDGEOTTO")] V0017PokemonPidgeotto = 17,
        [pbr::OriginalName("V0018_POKEMON_PIDGEOT")] V0018PokemonPidgeot = 18,
        [pbr::OriginalName("V0019_POKEMON_RATTATA")] V0019PokemonRattata = 19,
        [pbr::OriginalName("V0020_POKEMON_RATICATE")] V0020PokemonRaticate = 20,
        [pbr::OriginalName("V0021_POKEMON_SPEAROW")] V0021PokemonSpearow = 21,
        [pbr::OriginalName("V0022_POKEMON_FEAROW")] V0022PokemonFearow = 22,
        [pbr::OriginalName("V0023_POKEMON_EKANS")] V0023PokemonEkans = 23,
        [pbr::OriginalName("V0024_POKEMON_ARBOK")] V0024PokemonArbok = 24,
        [pbr::OriginalName("V0025_POKEMON_PIKACHU")] V0025PokemonPikachu = 25,
        [pbr::OriginalName("V0026_POKEMON_RAICHU")] V0026PokemonRaichu = 26,
        [pbr::OriginalName("V0027_POKEMON_SANDSHREW")] V0027PokemonSandshrew = 27,
        [pbr::OriginalName("V0028_POKEMON_SANDSLASH")] V0028PokemonSandslash = 28,
        [pbr::OriginalName("V0029_POKEMON_NIDORAN")] V0029PokemonNidoran = 29,
        [pbr::OriginalName("V0030_POKEMON_NIDORINA")] V0030PokemonNidorina = 30,
        [pbr::OriginalName("V0031_POKEMON_NIDOQUEEN")] V0031PokemonNidoqueen = 31,
        [pbr::OriginalName("V0032_POKEMON_NIDORAN")] V0032PokemonNidoran = 32,
        [pbr::OriginalName("V0033_POKEMON_NIDORINO")] V0033PokemonNidorino = 33,
        [pbr::OriginalName("V0034_POKEMON_NIDOKING")] V0034PokemonNidoking = 34,
        [pbr::OriginalName("V0035_POKEMON_CLEFAIRY")] V0035PokemonClefairy = 35,
        [pbr::OriginalName("V0036_POKEMON_CLEFABLE")] V0036PokemonClefable = 36,
        [pbr::OriginalName("V0037_POKEMON_VULPIX")] V0037PokemonVulpix = 37,
        [pbr::OriginalName("V0038_POKEMON_NINETALES")] V0038PokemonNinetales = 38,
        [pbr::OriginalName("V0039_POKEMON_JIGGLYPUFF")] V0039PokemonJigglypuff = 39,
        [pbr::OriginalName("V0040_POKEMON_WIGGLYTUFF")] V0040PokemonWigglytuff = 40,
        [pbr::OriginalName("V0041_POKEMON_ZUBAT")] V0041PokemonZubat = 41,
        [pbr::OriginalName("V0042_POKEMON_GOLBAT")] V0042PokemonGolbat = 42,
        [pbr::OriginalName("V0043_POKEMON_ODDISH")] V0043PokemonOddish = 43,
        [pbr::OriginalName("V0044_POKEMON_GLOOM")] V0044PokemonGloom = 44,
        [pbr::OriginalName("V0045_POKEMON_VILEPLUME")] V0045PokemonVileplume = 45,
        [pbr::OriginalName("V0046_POKEMON_PARAS")] V0046PokemonParas = 46,
        [pbr::OriginalName("V0047_POKEMON_PARASECT")] V0047PokemonParasect = 47,
        [pbr::OriginalName("V0048_POKEMON_VENONAT")] V0048PokemonVenonat = 48,
        [pbr::OriginalName("V0049_POKEMON_VENOMOTH")] V0049PokemonVenomoth = 49,
        [pbr::OriginalName("V0050_POKEMON_DIGLETT")] V0050PokemonDiglett = 50,
        [pbr::OriginalName("V0051_POKEMON_DUGTRIO")] V0051PokemonDugtrio = 51,
        [pbr::OriginalName("V0052_POKEMON_MEOWTH")] V0052PokemonMeowth = 52,
        [pbr::OriginalName("V0053_POKEMON_PERSIAN")] V0053PokemonPersian = 53,
        [pbr::OriginalName("V0054_POKEMON_PSYDUCK")] V0054PokemonPsyduck = 54,
        [pbr::OriginalName("V0055_POKEMON_GOLDUCK")] V0055PokemonGolduck = 55,
        [pbr::OriginalName("V0056_POKEMON_MANKEY")] V0056PokemonMankey = 56,
        [pbr::OriginalName("V0057_POKEMON_PRIMEAPE")] V0057PokemonPrimeape = 57,
        [pbr::OriginalName("V0058_POKEMON_GROWLITHE")] V0058PokemonGrowlithe = 58,
        [pbr::OriginalName("V0059_POKEMON_ARCANINE")] V0059PokemonArcanine = 59,
        [pbr::OriginalName("V0060_POKEMON_POLIWAG")] V0060PokemonPoliwag = 60,
        [pbr::OriginalName("V0061_POKEMON_POLIWHIRL")] V0061PokemonPoliwhirl = 61,
        [pbr::OriginalName("V0062_POKEMON_POLIWRATH")] V0062PokemonPoliwrath = 62,
        [pbr::OriginalName("V0063_POKEMON_ABRA")] V0063PokemonAbra = 63,
        [pbr::OriginalName("V0064_POKEMON_KADABRA")] V0064PokemonKadabra = 64,
        [pbr::OriginalName("V0065_POKEMON_ALAKAZAM")] V0065PokemonAlakazam = 65,
        [pbr::OriginalName("V0066_POKEMON_MACHOP")] V0066PokemonMachop = 66,
        [pbr::OriginalName("V0067_POKEMON_MACHOKE")] V0067PokemonMachoke = 67,
        [pbr::OriginalName("V0068_POKEMON_MACHAMP")] V0068PokemonMachamp = 68,
        [pbr::OriginalName("V0069_POKEMON_BELLSPROUT")] V0069PokemonBellsprout = 69,
        [pbr::OriginalName("V0070_POKEMON_WEEPINBELL")] V0070PokemonWeepinbell = 70,
        [pbr::OriginalName("V0071_POKEMON_VICTREEBEL")] V0071PokemonVictreebel = 71,
        [pbr::OriginalName("V0072_POKEMON_TENTACOOL")] V0072PokemonTentacool = 72,
        [pbr::OriginalName("V0073_POKEMON_TENTACRUEL")] V0073PokemonTentacruel = 73,
        [pbr::OriginalName("V0074_POKEMON_GEODUDE")] V0074PokemonGeodude = 74,
        [pbr::OriginalName("V0075_POKEMON_GRAVELER")] V0075PokemonGraveler = 75,
        [pbr::OriginalName("V0076_POKEMON_GOLEM")] V0076PokemonGolem = 76,
        [pbr::OriginalName("V0077_POKEMON_PONYTA")] V0077PokemonPonyta = 77,
        [pbr::OriginalName("V0078_POKEMON_RAPIDASH")] V0078PokemonRapidash = 78,
        [pbr::OriginalName("V0079_POKEMON_SLOWPOKE")] V0079PokemonSlowpoke = 79,
        [pbr::OriginalName("V0080_POKEMON_SLOWBRO")] V0080PokemonSlowbro = 80,
        [pbr::OriginalName("V0081_POKEMON_MAGNEMITE")] V0081PokemonMagnemite = 81,
        [pbr::OriginalName("V0082_POKEMON_MAGNETON")] V0082PokemonMagneton = 82,
        [pbr::OriginalName("V0083_POKEMON_FARFETCHD")] V0083PokemonFarfetchd = 83,
        [pbr::OriginalName("V0084_POKEMON_DODUO")] V0084PokemonDoduo = 84,
        [pbr::OriginalName("V0085_POKEMON_DODRIO")] V0085PokemonDodrio = 85,
        [pbr::OriginalName("V0086_POKEMON_SEEL")] V0086PokemonSeel = 86,
        [pbr::OriginalName("V0087_POKEMON_DEWGONG")] V0087PokemonDewgong = 87,
        [pbr::OriginalName("V0088_POKEMON_GRIMER")] V0088PokemonGrimer = 88,
        [pbr::OriginalName("V0089_POKEMON_MUK")] V0089PokemonMuk = 89,
        [pbr::OriginalName("V0090_POKEMON_SHELLDER")] V0090PokemonShellder = 90,
        [pbr::OriginalName("V0091_POKEMON_CLOYSTER")] V0091PokemonCloyster = 91,
        [pbr::OriginalName("V0092_POKEMON_GASTLY")] V0092PokemonGastly = 92,
        [pbr::OriginalName("V0093_POKEMON_HAUNTER")] V0093PokemonHaunter = 93,
        [pbr::OriginalName("V0094_POKEMON_GENGAR")] V0094PokemonGengar = 94,
        [pbr::OriginalName("V0095_POKEMON_ONIX")] V0095PokemonOnix = 95,
        [pbr::OriginalName("V0096_POKEMON_DROWZEE")] V0096PokemonDrowzee = 96,
        [pbr::OriginalName("V0097_POKEMON_HYPNO")] V0097PokemonHypno = 97,
        [pbr::OriginalName("V0098_POKEMON_KRABBY")] V0098PokemonKrabby = 98,
        [pbr::OriginalName("V0099_POKEMON_KINGLER")] V0099PokemonKingler = 99,
        [pbr::OriginalName("V0100_POKEMON_VOLTORB")] V0100PokemonVoltorb = 100,
        [pbr::OriginalName("V0101_POKEMON_ELECTRODE")] V0101PokemonElectrode = 101,
        [pbr::OriginalName("V0102_POKEMON_EXEGGCUTE")] V0102PokemonExeggcute = 102,
        [pbr::OriginalName("V0103_POKEMON_EXEGGUTOR")] V0103PokemonExeggutor = 103,
        [pbr::OriginalName("V0104_POKEMON_CUBONE")] V0104PokemonCubone = 104,
        [pbr::OriginalName("V0105_POKEMON_MAROWAK")] V0105PokemonMarowak = 105,
        [pbr::OriginalName("V0106_POKEMON_HITMONLEE")] V0106PokemonHitmonlee = 106,
        [pbr::OriginalName("V0107_POKEMON_HITMONCHAN")] V0107PokemonHitmonchan = 107,
        [pbr::OriginalName("V0108_POKEMON_LICKITUNG")] V0108PokemonLickitung = 108,
        [pbr::OriginalName("V0109_POKEMON_KOFFING")] V0109PokemonKoffing = 109,
        [pbr::OriginalName("V0110_POKEMON_WEEZING")] V0110PokemonWeezing = 110,
        [pbr::OriginalName("V0111_POKEMON_RHYHORN")] V0111PokemonRhyhorn = 111,
        [pbr::OriginalName("V0112_POKEMON_RHYDON")] V0112PokemonRhydon = 112,
        [pbr::OriginalName("V0113_POKEMON_CHANSEY")] V0113PokemonChansey = 113,
        [pbr::OriginalName("V0114_POKEMON_TANGELA")] V0114PokemonTangela = 114,
        [pbr::OriginalName("V0115_POKEMON_KANGASKHAN")] V0115PokemonKangaskhan = 115,
        [pbr::OriginalName("V0116_POKEMON_HORSEA")] V0116PokemonHorsea = 116,
        [pbr::OriginalName("V0117_POKEMON_SEADRA")] V0117PokemonSeadra = 117,
        [pbr::OriginalName("V0118_POKEMON_GOLDEEN")] V0118PokemonGoldeen = 118,
        [pbr::OriginalName("V0119_POKEMON_SEAKING")] V0119PokemonSeaking = 119,
        [pbr::OriginalName("V0120_POKEMON_STARYU")] V0120PokemonStaryu = 120,
        [pbr::OriginalName("V0121_POKEMON_STARMIE")] V0121PokemonStarmie = 121,
        [pbr::OriginalName("V0122_POKEMON_MR_MIME")] V0122PokemonMrMime = 122,
        [pbr::OriginalName("V0123_POKEMON_SCYTHER")] V0123PokemonScyther = 123,
        [pbr::OriginalName("V0124_POKEMON_JYNX")] V0124PokemonJynx = 124,
        [pbr::OriginalName("V0125_POKEMON_ELECTABUZZ")] V0125PokemonElectabuzz = 125,
        [pbr::OriginalName("V0126_POKEMON_MAGMAR")] V0126PokemonMagmar = 126,
        [pbr::OriginalName("V0127_POKEMON_PINSIR")] V0127PokemonPinsir = 127,
        [pbr::OriginalName("V0128_POKEMON_TAUROS")] V0128PokemonTauros = 128,
        [pbr::OriginalName("V0129_POKEMON_MAGIKARP")] V0129PokemonMagikarp = 129,
        [pbr::OriginalName("V0130_POKEMON_GYARADOS")] V0130PokemonGyarados = 130,
        [pbr::OriginalName("V0131_POKEMON_LAPRAS")] V0131PokemonLapras = 131,
        [pbr::OriginalName("V0132_POKEMON_DITTO")] V0132PokemonDitto = 132,
        [pbr::OriginalName("V0133_POKEMON_EEVEE")] V0133PokemonEevee = 133,
        [pbr::OriginalName("V0134_POKEMON_VAPOREON")] V0134PokemonVaporeon = 134,
        [pbr::OriginalName("V0135_POKEMON_JOLTEON")] V0135PokemonJolteon = 135,
        [pbr::OriginalName("V0136_POKEMON_FLAREON")] V0136PokemonFlareon = 136,
        [pbr::OriginalName("V0137_POKEMON_PORYGON")] V0137PokemonPorygon = 137,
        [pbr::OriginalName("V0138_POKEMON_OMANYTE")] V0138PokemonOmanyte = 138,
        [pbr::OriginalName("V0139_POKEMON_OMASTAR")] V0139PokemonOmastar = 139,
        [pbr::OriginalName("V0140_POKEMON_KABUTO")] V0140PokemonKabuto = 140,
        [pbr::OriginalName("V0141_POKEMON_KABUTOPS")] V0141PokemonKabutops = 141,
        [pbr::OriginalName("V0142_POKEMON_AERODACTYL")] V0142PokemonAerodactyl = 142,
        [pbr::OriginalName("V0143_POKEMON_SNORLAX")] V0143PokemonSnorlax = 143,
        [pbr::OriginalName("V0144_POKEMON_ARTICUNO")] V0144PokemonArticuno = 144,
        [pbr::OriginalName("V0145_POKEMON_ZAPDOS")] V0145PokemonZapdos = 145,
        [pbr::OriginalName("V0146_POKEMON_MOLTRES")] V0146PokemonMoltres = 146,
        [pbr::OriginalName("V0147_POKEMON_DRATINI")] V0147PokemonDratini = 147,
        [pbr::OriginalName("V0148_POKEMON_DRAGONAIR")] V0148PokemonDragonair = 148,
        [pbr::OriginalName("V0149_POKEMON_DRAGONITE")] V0149PokemonDragonite = 149,
        [pbr::OriginalName("V0150_POKEMON_MEWTWO")] V0150PokemonMewtwo = 150,
        [pbr::OriginalName("V0151_POKEMON_MEW")] V0151PokemonMew = 151,
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
      public sealed partial class Unknown6 : pb::IMessage<Unknown6> {
        private static readonly pb::MessageParser<Unknown6> _parser = new pb::MessageParser<Unknown6>(() => new Unknown6());
        public static pb::MessageParser<Unknown6> Parser { get { return _parser; } }

        public static pbr::MessageDescriptor Descriptor {
          get { return global::PokemonGo.RocketAPI.GeneratedCode.CatchPokemonResponse.Descriptor.NestedTypes[0]; }
        }

        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        public Unknown6() {
          OnConstruction();
        }

        partial void OnConstruction();

        public Unknown6(Unknown6 other) : this() {
          unknown1_ = other.unknown1_;
          Unknown2 = other.unknown2_ != null ? other.Unknown2.Clone() : null;
        }

        public Unknown6 Clone() {
          return new Unknown6(this);
        }

        /// <summary>Field number for the "unknown1" field.</summary>
        public const int Unknown1FieldNumber = 1;
        private int unknown1_;
        public int Unknown1 {
          get { return unknown1_; }
          set {
            unknown1_ = value;
          }
        }

        /// <summary>Field number for the "unknown2" field.</summary>
        public const int Unknown2FieldNumber = 2;
        private global::PokemonGo.RocketAPI.GeneratedCode.CatchPokemonResponse.Types.Unknown6.Types.Unknown2 unknown2_;
        public global::PokemonGo.RocketAPI.GeneratedCode.CatchPokemonResponse.Types.Unknown6.Types.Unknown2 Unknown2 {
          get { return unknown2_; }
          set {
            unknown2_ = value;
          }
        }

        public override bool Equals(object other) {
          return Equals(other as Unknown6);
        }

        public bool Equals(Unknown6 other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Unknown1 != other.Unknown1) return false;
          if (!object.Equals(Unknown2, other.Unknown2)) return false;
          return true;
        }

        public override int GetHashCode() {
          int hash = 1;
          if (Unknown1 != 0) hash ^= Unknown1.GetHashCode();
          if (unknown2_ != null) hash ^= Unknown2.GetHashCode();
          return hash;
        }

        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        public void WriteTo(pb::CodedOutputStream output) {
          if (Unknown1 != 0) {
            output.WriteRawTag(8);
            output.WriteInt32(Unknown1);
          }
          if (unknown2_ != null) {
            output.WriteRawTag(18);
            output.WriteMessage(Unknown2);
          }
        }

        public int CalculateSize() {
          int size = 0;
          if (Unknown1 != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(Unknown1);
          }
          if (unknown2_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(Unknown2);
          }
          return size;
        }

        public void MergeFrom(Unknown6 other) {
          if (other == null) {
            return;
          }
          if (other.Unknown1 != 0) {
            Unknown1 = other.Unknown1;
          }
          if (other.unknown2_ != null) {
            if (unknown2_ == null) {
              unknown2_ = new global::PokemonGo.RocketAPI.GeneratedCode.CatchPokemonResponse.Types.Unknown6.Types.Unknown2();
            }
            Unknown2.MergeFrom(other.Unknown2);
          }
        }

        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                input.SkipLastField();
                break;
              case 8: {
                Unknown1 = input.ReadInt32();
                break;
              }
              case 18: {
                if (unknown2_ == null) {
                  unknown2_ = new global::PokemonGo.RocketAPI.GeneratedCode.CatchPokemonResponse.Types.Unknown6.Types.Unknown2();
                }
                input.ReadMessage(unknown2_);
                break;
              }
            }
          }
        }

        #region Nested types
        /// <summary>Container for nested types declared in the Unknown6 message type.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static partial class Types {
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
          public sealed partial class Unknown2 : pb::IMessage<Unknown2> {
            private static readonly pb::MessageParser<Unknown2> _parser = new pb::MessageParser<Unknown2>(() => new Unknown2());
            public static pb::MessageParser<Unknown2> Parser { get { return _parser; } }

            public static pbr::MessageDescriptor Descriptor {
              get { return global::PokemonGo.RocketAPI.GeneratedCode.CatchPokemonResponse.Types.Unknown6.Descriptor.NestedTypes[0]; }
            }

            pbr::MessageDescriptor pb::IMessage.Descriptor {
              get { return Descriptor; }
            }

            public Unknown2() {
              OnConstruction();
            }

            partial void OnConstruction();

            public Unknown2(Unknown2 other) : this() {
              unknown1_ = other.unknown1_;
            }

            public Unknown2 Clone() {
              return new Unknown2(this);
            }

            /// <summary>Field number for the "unknown1" field.</summary>
            public const int Unknown1FieldNumber = 1;
            private pb::ByteString unknown1_ = pb::ByteString.Empty;
            public pb::ByteString Unknown1 {
              get { return unknown1_; }
              set {
                unknown1_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
              }
            }

            public override bool Equals(object other) {
              return Equals(other as Unknown2);
            }

            public bool Equals(Unknown2 other) {
              if (ReferenceEquals(other, null)) {
                return false;
              }
              if (ReferenceEquals(other, this)) {
                return true;
              }
              if (Unknown1 != other.Unknown1) return false;
              return true;
            }

            public override int GetHashCode() {
              int hash = 1;
              if (Unknown1.Length != 0) hash ^= Unknown1.GetHashCode();
              return hash;
            }

            public override string ToString() {
              return pb::JsonFormatter.ToDiagnosticString(this);
            }

            public void WriteTo(pb::CodedOutputStream output) {
              if (Unknown1.Length != 0) {
                output.WriteRawTag(10);
                output.WriteBytes(Unknown1);
              }
            }

            public int CalculateSize() {
              int size = 0;
              if (Unknown1.Length != 0) {
                size += 1 + pb::CodedOutputStream.ComputeBytesSize(Unknown1);
              }
              return size;
            }

            public void MergeFrom(Unknown2 other) {
              if (other == null) {
                return;
              }
              if (other.Unknown1.Length != 0) {
                Unknown1 = other.Unknown1;
              }
            }

            public void MergeFrom(pb::CodedInputStream input) {
              uint tag;
              while ((tag = input.ReadTag()) != 0) {
                switch(tag) {
                  default:
                    input.SkipLastField();
                    break;
                  case 10: {
                    Unknown1 = input.ReadBytes();
                    break;
                  }
                }
              }
            }

          }

        }
        #endregion

      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
      public sealed partial class Unknown7 : pb::IMessage<Unknown7> {
        private static readonly pb::MessageParser<Unknown7> _parser = new pb::MessageParser<Unknown7>(() => new Unknown7());
        public static pb::MessageParser<Unknown7> Parser { get { return _parser; } }

        public static pbr::MessageDescriptor Descriptor {
          get { return global::PokemonGo.RocketAPI.GeneratedCode.CatchPokemonResponse.Descriptor.NestedTypes[1]; }
        }

        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        public Unknown7() {
          OnConstruction();
        }

        partial void OnConstruction();

        public Unknown7(Unknown7 other) : this() {
          unknown71_ = other.unknown71_;
          unknown72_ = other.unknown72_;
          unknown73_ = other.unknown73_;
        }

        public Unknown7 Clone() {
          return new Unknown7(this);
        }

        /// <summary>Field number for the "unknown71" field.</summary>
        public const int Unknown71FieldNumber = 1;
        private pb::ByteString unknown71_ = pb::ByteString.Empty;
        public pb::ByteString Unknown71 {
          get { return unknown71_; }
          set {
            unknown71_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "unknown72" field.</summary>
        public const int Unknown72FieldNumber = 2;
        private long unknown72_;
        public long Unknown72 {
          get { return unknown72_; }
          set {
            unknown72_ = value;
          }
        }

        /// <summary>Field number for the "unknown73" field.</summary>
        public const int Unknown73FieldNumber = 3;
        private pb::ByteString unknown73_ = pb::ByteString.Empty;
        public pb::ByteString Unknown73 {
          get { return unknown73_; }
          set {
            unknown73_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        public override bool Equals(object other) {
          return Equals(other as Unknown7);
        }

        public bool Equals(Unknown7 other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Unknown71 != other.Unknown71) return false;
          if (Unknown72 != other.Unknown72) return false;
          if (Unknown73 != other.Unknown73) return false;
          return true;
        }

        public override int GetHashCode() {
          int hash = 1;
          if (Unknown71.Length != 0) hash ^= Unknown71.GetHashCode();
          if (Unknown72 != 0L) hash ^= Unknown72.GetHashCode();
          if (Unknown73.Length != 0) hash ^= Unknown73.GetHashCode();
          return hash;
        }

        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        public void WriteTo(pb::CodedOutputStream output) {
          if (Unknown71.Length != 0) {
            output.WriteRawTag(10);
            output.WriteBytes(Unknown71);
          }
          if (Unknown72 != 0L) {
            output.WriteRawTag(16);
            output.WriteInt64(Unknown72);
          }
          if (Unknown73.Length != 0) {
            output.WriteRawTag(26);
            output.WriteBytes(Unknown73);
          }
        }

        public int CalculateSize() {
          int size = 0;
          if (Unknown71.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeBytesSize(Unknown71);
          }
          if (Unknown72 != 0L) {
            size += 1 + pb::CodedOutputStream.ComputeInt64Size(Unknown72);
          }
          if (Unknown73.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeBytesSize(Unknown73);
          }
          return size;
        }

        public void MergeFrom(Unknown7 other) {
          if (other == null) {
            return;
          }
          if (other.Unknown71.Length != 0) {
            Unknown71 = other.Unknown71;
          }
          if (other.Unknown72 != 0L) {
            Unknown72 = other.Unknown72;
          }
          if (other.Unknown73.Length != 0) {
            Unknown73 = other.Unknown73;
          }
        }

        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                input.SkipLastField();
                break;
              case 10: {
                Unknown71 = input.ReadBytes();
                break;
              }
              case 16: {
                Unknown72 = input.ReadInt64();
                break;
              }
              case 26: {
                Unknown73 = input.ReadBytes();
                break;
              }
            }
          }
        }

      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
      public sealed partial class Payload : pb::IMessage<Payload> {
        private static readonly pb::MessageParser<Payload> _parser = new pb::MessageParser<Payload>(() => new Payload());
        public static pb::MessageParser<Payload> Parser { get { return _parser; } }

        public static pbr::MessageDescriptor Descriptor {
          get { return global::PokemonGo.RocketAPI.GeneratedCode.CatchPokemonResponse.Descriptor.NestedTypes[2]; }
        }

        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        public Payload() {
          OnConstruction();
        }

        partial void OnConstruction();

        public Payload(Payload other) : this() {
          status_ = other.status_;
          missPercent_ = other.missPercent_;
          capturedPokemonId_ = other.capturedPokemonId_;
          scores_ = other.scores_;
        }

        public Payload Clone() {
          return new Payload(this);
        }

        /// <summary>Field number for the "Status" field.</summary>
        public const int StatusFieldNumber = 1;
        private int status_;
        public int Status {
          get { return status_; }
          set {
            status_ = value;
          }
        }

        /// <summary>Field number for the "MissPercent" field.</summary>
        public const int MissPercentFieldNumber = 2;
        private ulong missPercent_;
        public ulong MissPercent {
          get { return missPercent_; }
          set {
            missPercent_ = value;
          }
        }

        /// <summary>Field number for the "CapturedPokemonId" field.</summary>
        public const int CapturedPokemonIdFieldNumber = 3;
        private global::PokemonGo.RocketAPI.GeneratedCode.CatchPokemonResponse.Types.PokemonIds capturedPokemonId_ = 0;
        public global::PokemonGo.RocketAPI.GeneratedCode.CatchPokemonResponse.Types.PokemonIds CapturedPokemonId {
          get { return capturedPokemonId_; }
          set {
            capturedPokemonId_ = value;
          }
        }

        /// <summary>Field number for the "Scores" field.</summary>
        public const int ScoresFieldNumber = 4;
        private int scores_;
        public int Scores {
          get { return scores_; }
          set {
            scores_ = value;
          }
        }

        public override bool Equals(object other) {
          return Equals(other as Payload);
        }

        public bool Equals(Payload other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Status != other.Status) return false;
          if (MissPercent != other.MissPercent) return false;
          if (CapturedPokemonId != other.CapturedPokemonId) return false;
          if (Scores != other.Scores) return false;
          return true;
        }

        public override int GetHashCode() {
          int hash = 1;
          if (Status != 0) hash ^= Status.GetHashCode();
          if (MissPercent != 0UL) hash ^= MissPercent.GetHashCode();
          if (CapturedPokemonId != 0) hash ^= CapturedPokemonId.GetHashCode();
          if (Scores != 0) hash ^= Scores.GetHashCode();
          return hash;
        }

        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        public void WriteTo(pb::CodedOutputStream output) {
          if (Status != 0) {
            output.WriteRawTag(8);
            output.WriteInt32(Status);
          }
          if (MissPercent != 0UL) {
            output.WriteRawTag(17);
            output.WriteFixed64(MissPercent);
          }
          if (CapturedPokemonId != 0) {
            output.WriteRawTag(24);
            output.WriteEnum((int) CapturedPokemonId);
          }
          if (Scores != 0) {
            output.WriteRawTag(32);
            output.WriteInt32(Scores);
          }
        }

        public int CalculateSize() {
          int size = 0;
          if (Status != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(Status);
          }
          if (MissPercent != 0UL) {
            size += 1 + 8;
          }
          if (CapturedPokemonId != 0) {
            size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) CapturedPokemonId);
          }
          if (Scores != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(Scores);
          }
          return size;
        }

        public void MergeFrom(Payload other) {
          if (other == null) {
            return;
          }
          if (other.Status != 0) {
            Status = other.Status;
          }
          if (other.MissPercent != 0UL) {
            MissPercent = other.MissPercent;
          }
          if (other.CapturedPokemonId != 0) {
            CapturedPokemonId = other.CapturedPokemonId;
          }
          if (other.Scores != 0) {
            Scores = other.Scores;
          }
        }

        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                input.SkipLastField();
                break;
              case 8: {
                Status = input.ReadInt32();
                break;
              }
              case 17: {
                MissPercent = input.ReadFixed64();
                break;
              }
              case 24: {
                capturedPokemonId_ = (global::PokemonGo.RocketAPI.GeneratedCode.CatchPokemonResponse.Types.PokemonIds) input.ReadEnum();
                break;
              }
              case 32: {
                Scores = input.ReadInt32();
                break;
              }
            }
          }
        }

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
