// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FortDetailResponse.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace PokemonGo.RocketAPI.GeneratedCode {

  /// <summary>Holder for reflection information generated from FortDetailResponse.proto</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class FortDetailResponseReflection {

    #region Descriptor
    /// <summary>File descriptor for FortDetailResponse.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FortDetailResponseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChhGb3J0RGV0YWlsUmVzcG9uc2UucHJvdG8SIVBva2Vtb25Hby5Sb2NrZXRB",
            "UEkuR2VuZXJhdGVkQ29kZSKWBgoSRm9ydERldGFpbFJlc3BvbnNlEhAKCHVu",
            "a25vd24xGAEgASgFEhAKCHVua25vd24yGAIgASgDEg8KB2FwaV91cmwYAyAB",
            "KAkSUAoIdW5rbm93bjYYBiABKAsyPi5Qb2tlbW9uR28uUm9ja2V0QVBJLkdl",
            "bmVyYXRlZENvZGUuRm9ydERldGFpbFJlc3BvbnNlLlVua25vd242ElAKCHVu",
            "a25vd243GAcgASgLMj4uUG9rZW1vbkdvLlJvY2tldEFQSS5HZW5lcmF0ZWRD",
            "b2RlLkZvcnREZXRhaWxSZXNwb25zZS5Vbmtub3duNxJOCgdwYXlsb2FkGGQg",
            "AygLMj0uUG9rZW1vbkdvLlJvY2tldEFQSS5HZW5lcmF0ZWRDb2RlLkZvcnRE",
            "ZXRhaWxSZXNwb25zZS5QYXlsb2FkEhQKDGVycm9yTWVzc2FnZRhlIAEoCRqV",
            "AQoIVW5rbm93bjYSEAoIdW5rbm93bjEYASABKAUSWQoIdW5rbm93bjIYAiAB",
            "KAsyRy5Qb2tlbW9uR28uUm9ja2V0QVBJLkdlbmVyYXRlZENvZGUuRm9ydERl",
            "dGFpbFJlc3BvbnNlLlVua25vd242LlVua25vd24yGhwKCFVua25vd24yEhAK",
            "CHVua25vd24xGAEgASgMGkMKCFVua25vd243EhEKCXVua25vd243MRgBIAEo",
            "DBIRCgl1bmtub3duNzIYAiABKAMSEQoJdW5rbm93bjczGAMgASgMGuMBCgdQ",
            "YXlsb2FkEgoKAklkGAEgASgJEgwKBFRlYW0YAiABKAUSDwoHUG9rZW1vbhgD",
            "IAEoBRIMCgROYW1lGAQgASgJEhAKCEltYWdlVXJsGAUgASgJEgoKAkZwGAYg",
            "ASgFEg8KB1N0YW1pbmEYByABKAUSEgoKTWF4U3RhbWluYRgIIAEoBRIQCghG",
            "b3J0VHlwZRgJIAEoBRIQCghMYXRpdHVkZRgKIAEoAxIRCglMb25naXR1ZGUY",
            "CyABKAMSEwoLRGVzY3JpcHRpb24YDCABKAkSEAoITW9kaWZpZXIYDSABKAVi",
            "BnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::PokemonGo.RocketAPI.GeneratedCode.FortDetailResponse), global::PokemonGo.RocketAPI.GeneratedCode.FortDetailResponse.Parser, new[]{ "Unknown1", "Unknown2", "ApiUrl", "Unknown6", "Unknown7", "Payload", "ErrorMessage" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::PokemonGo.RocketAPI.GeneratedCode.FortDetailResponse.Types.Unknown6), global::PokemonGo.RocketAPI.GeneratedCode.FortDetailResponse.Types.Unknown6.Parser, new[]{ "Unknown1", "Unknown2" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::PokemonGo.RocketAPI.GeneratedCode.FortDetailResponse.Types.Unknown6.Types.Unknown2), global::PokemonGo.RocketAPI.GeneratedCode.FortDetailResponse.Types.Unknown6.Types.Unknown2.Parser, new[]{ "Unknown1" }, null, null, null)}),
            new pbr::GeneratedClrTypeInfo(typeof(global::PokemonGo.RocketAPI.GeneratedCode.FortDetailResponse.Types.Unknown7), global::PokemonGo.RocketAPI.GeneratedCode.FortDetailResponse.Types.Unknown7.Parser, new[]{ "Unknown71", "Unknown72", "Unknown73" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::PokemonGo.RocketAPI.GeneratedCode.FortDetailResponse.Types.Payload), global::PokemonGo.RocketAPI.GeneratedCode.FortDetailResponse.Types.Payload.Parser, new[]{ "Id", "Team", "Pokemon", "Name", "ImageUrl", "Fp", "Stamina", "MaxStamina", "FortType", "Latitude", "Longitude", "Description", "Modifier" }, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class FortDetailResponse : pb::IMessage<FortDetailResponse> {
    private static readonly pb::MessageParser<FortDetailResponse> _parser = new pb::MessageParser<FortDetailResponse>(() => new FortDetailResponse());
    public static pb::MessageParser<FortDetailResponse> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::PokemonGo.RocketAPI.GeneratedCode.FortDetailResponseReflection.Descriptor.MessageTypes[0]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public FortDetailResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    public FortDetailResponse(FortDetailResponse other) : this() {
      unknown1_ = other.unknown1_;
      unknown2_ = other.unknown2_;
      apiUrl_ = other.apiUrl_;
      Unknown6 = other.unknown6_ != null ? other.Unknown6.Clone() : null;
      Unknown7 = other.unknown7_ != null ? other.Unknown7.Clone() : null;
      payload_ = other.payload_.Clone();
      errorMessage_ = other.errorMessage_;
    }

    public FortDetailResponse Clone() {
      return new FortDetailResponse(this);
    }

    /// <summary>Field number for the "unknown1" field.</summary>
    public const int Unknown1FieldNumber = 1;
    private int unknown1_;
    public int Unknown1 {
      get { return unknown1_; }
      set {
        unknown1_ = value;
      }
    }

    /// <summary>Field number for the "unknown2" field.</summary>
    public const int Unknown2FieldNumber = 2;
    private long unknown2_;
    public long Unknown2 {
      get { return unknown2_; }
      set {
        unknown2_ = value;
      }
    }

    /// <summary>Field number for the "api_url" field.</summary>
    public const int ApiUrlFieldNumber = 3;
    private string apiUrl_ = "";
    public string ApiUrl {
      get { return apiUrl_; }
      set {
        apiUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "unknown6" field.</summary>
    public const int Unknown6FieldNumber = 6;
    private global::PokemonGo.RocketAPI.GeneratedCode.FortDetailResponse.Types.Unknown6 unknown6_;
    public global::PokemonGo.RocketAPI.GeneratedCode.FortDetailResponse.Types.Unknown6 Unknown6 {
      get { return unknown6_; }
      set {
        unknown6_ = value;
      }
    }

    /// <summary>Field number for the "unknown7" field.</summary>
    public const int Unknown7FieldNumber = 7;
    private global::PokemonGo.RocketAPI.GeneratedCode.FortDetailResponse.Types.Unknown7 unknown7_;
    public global::PokemonGo.RocketAPI.GeneratedCode.FortDetailResponse.Types.Unknown7 Unknown7 {
      get { return unknown7_; }
      set {
        unknown7_ = value;
      }
    }

    /// <summary>Field number for the "payload" field.</summary>
    public const int PayloadFieldNumber = 100;
    private static readonly pb::FieldCodec<global::PokemonGo.RocketAPI.GeneratedCode.FortDetailResponse.Types.Payload> _repeated_payload_codec
        = pb::FieldCodec.ForMessage(802, global::PokemonGo.RocketAPI.GeneratedCode.FortDetailResponse.Types.Payload.Parser);
    private readonly pbc::RepeatedField<global::PokemonGo.RocketAPI.GeneratedCode.FortDetailResponse.Types.Payload> payload_ = new pbc::RepeatedField<global::PokemonGo.RocketAPI.GeneratedCode.FortDetailResponse.Types.Payload>();
    public pbc::RepeatedField<global::PokemonGo.RocketAPI.GeneratedCode.FortDetailResponse.Types.Payload> Payload {
      get { return payload_; }
    }

    /// <summary>Field number for the "errorMessage" field.</summary>
    public const int ErrorMessageFieldNumber = 101;
    private string errorMessage_ = "";
    /// <summary>
    /// Should be moved to an error-proto file if error is always 101 field
    /// </summary>
    public string ErrorMessage {
      get { return errorMessage_; }
      set {
        errorMessage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public override bool Equals(object other) {
      return Equals(other as FortDetailResponse);
    }

    public bool Equals(FortDetailResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Unknown1 != other.Unknown1) return false;
      if (Unknown2 != other.Unknown2) return false;
      if (ApiUrl != other.ApiUrl) return false;
      if (!object.Equals(Unknown6, other.Unknown6)) return false;
      if (!object.Equals(Unknown7, other.Unknown7)) return false;
      if(!payload_.Equals(other.payload_)) return false;
      if (ErrorMessage != other.ErrorMessage) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      if (Unknown1 != 0) hash ^= Unknown1.GetHashCode();
      if (Unknown2 != 0L) hash ^= Unknown2.GetHashCode();
      if (ApiUrl.Length != 0) hash ^= ApiUrl.GetHashCode();
      if (unknown6_ != null) hash ^= Unknown6.GetHashCode();
      if (unknown7_ != null) hash ^= Unknown7.GetHashCode();
      hash ^= payload_.GetHashCode();
      if (ErrorMessage.Length != 0) hash ^= ErrorMessage.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (Unknown1 != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Unknown1);
      }
      if (Unknown2 != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Unknown2);
      }
      if (ApiUrl.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ApiUrl);
      }
      if (unknown6_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Unknown6);
      }
      if (unknown7_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(Unknown7);
      }
      payload_.WriteTo(output, _repeated_payload_codec);
      if (ErrorMessage.Length != 0) {
        output.WriteRawTag(170, 6);
        output.WriteString(ErrorMessage);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (Unknown1 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Unknown1);
      }
      if (Unknown2 != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Unknown2);
      }
      if (ApiUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ApiUrl);
      }
      if (unknown6_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Unknown6);
      }
      if (unknown7_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Unknown7);
      }
      size += payload_.CalculateSize(_repeated_payload_codec);
      if (ErrorMessage.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(ErrorMessage);
      }
      return size;
    }

    public void MergeFrom(FortDetailResponse other) {
      if (other == null) {
        return;
      }
      if (other.Unknown1 != 0) {
        Unknown1 = other.Unknown1;
      }
      if (other.Unknown2 != 0L) {
        Unknown2 = other.Unknown2;
      }
      if (other.ApiUrl.Length != 0) {
        ApiUrl = other.ApiUrl;
      }
      if (other.unknown6_ != null) {
        if (unknown6_ == null) {
          unknown6_ = new global::PokemonGo.RocketAPI.GeneratedCode.FortDetailResponse.Types.Unknown6();
        }
        Unknown6.MergeFrom(other.Unknown6);
      }
      if (other.unknown7_ != null) {
        if (unknown7_ == null) {
          unknown7_ = new global::PokemonGo.RocketAPI.GeneratedCode.FortDetailResponse.Types.Unknown7();
        }
        Unknown7.MergeFrom(other.Unknown7);
      }
      payload_.Add(other.payload_);
      if (other.ErrorMessage.Length != 0) {
        ErrorMessage = other.ErrorMessage;
      }
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Unknown1 = input.ReadInt32();
            break;
          }
          case 16: {
            Unknown2 = input.ReadInt64();
            break;
          }
          case 26: {
            ApiUrl = input.ReadString();
            break;
          }
          case 50: {
            if (unknown6_ == null) {
              unknown6_ = new global::PokemonGo.RocketAPI.GeneratedCode.FortDetailResponse.Types.Unknown6();
            }
            input.ReadMessage(unknown6_);
            break;
          }
          case 58: {
            if (unknown7_ == null) {
              unknown7_ = new global::PokemonGo.RocketAPI.GeneratedCode.FortDetailResponse.Types.Unknown7();
            }
            input.ReadMessage(unknown7_);
            break;
          }
          case 802: {
            payload_.AddEntriesFrom(input, _repeated_payload_codec);
            break;
          }
          case 810: {
            ErrorMessage = input.ReadString();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the FortDetailResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public static partial class Types {
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
      public sealed partial class Unknown6 : pb::IMessage<Unknown6> {
        private static readonly pb::MessageParser<Unknown6> _parser = new pb::MessageParser<Unknown6>(() => new Unknown6());
        public static pb::MessageParser<Unknown6> Parser { get { return _parser; } }

        public static pbr::MessageDescriptor Descriptor {
          get { return global::PokemonGo.RocketAPI.GeneratedCode.FortDetailResponse.Descriptor.NestedTypes[0]; }
        }

        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        public Unknown6() {
          OnConstruction();
        }

        partial void OnConstruction();

        public Unknown6(Unknown6 other) : this() {
          unknown1_ = other.unknown1_;
          Unknown2 = other.unknown2_ != null ? other.Unknown2.Clone() : null;
        }

        public Unknown6 Clone() {
          return new Unknown6(this);
        }

        /// <summary>Field number for the "unknown1" field.</summary>
        public const int Unknown1FieldNumber = 1;
        private int unknown1_;
        public int Unknown1 {
          get { return unknown1_; }
          set {
            unknown1_ = value;
          }
        }

        /// <summary>Field number for the "unknown2" field.</summary>
        public const int Unknown2FieldNumber = 2;
        private global::PokemonGo.RocketAPI.GeneratedCode.FortDetailResponse.Types.Unknown6.Types.Unknown2 unknown2_;
        public global::PokemonGo.RocketAPI.GeneratedCode.FortDetailResponse.Types.Unknown6.Types.Unknown2 Unknown2 {
          get { return unknown2_; }
          set {
            unknown2_ = value;
          }
        }

        public override bool Equals(object other) {
          return Equals(other as Unknown6);
        }

        public bool Equals(Unknown6 other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Unknown1 != other.Unknown1) return false;
          if (!object.Equals(Unknown2, other.Unknown2)) return false;
          return true;
        }

        public override int GetHashCode() {
          int hash = 1;
          if (Unknown1 != 0) hash ^= Unknown1.GetHashCode();
          if (unknown2_ != null) hash ^= Unknown2.GetHashCode();
          return hash;
        }

        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        public void WriteTo(pb::CodedOutputStream output) {
          if (Unknown1 != 0) {
            output.WriteRawTag(8);
            output.WriteInt32(Unknown1);
          }
          if (unknown2_ != null) {
            output.WriteRawTag(18);
            output.WriteMessage(Unknown2);
          }
        }

        public int CalculateSize() {
          int size = 0;
          if (Unknown1 != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(Unknown1);
          }
          if (unknown2_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(Unknown2);
          }
          return size;
        }

        public void MergeFrom(Unknown6 other) {
          if (other == null) {
            return;
          }
          if (other.Unknown1 != 0) {
            Unknown1 = other.Unknown1;
          }
          if (other.unknown2_ != null) {
            if (unknown2_ == null) {
              unknown2_ = new global::PokemonGo.RocketAPI.GeneratedCode.FortDetailResponse.Types.Unknown6.Types.Unknown2();
            }
            Unknown2.MergeFrom(other.Unknown2);
          }
        }

        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                input.SkipLastField();
                break;
              case 8: {
                Unknown1 = input.ReadInt32();
                break;
              }
              case 18: {
                if (unknown2_ == null) {
                  unknown2_ = new global::PokemonGo.RocketAPI.GeneratedCode.FortDetailResponse.Types.Unknown6.Types.Unknown2();
                }
                input.ReadMessage(unknown2_);
                break;
              }
            }
          }
        }

        #region Nested types
        /// <summary>Container for nested types declared in the Unknown6 message type.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static partial class Types {
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
          public sealed partial class Unknown2 : pb::IMessage<Unknown2> {
            private static readonly pb::MessageParser<Unknown2> _parser = new pb::MessageParser<Unknown2>(() => new Unknown2());
            public static pb::MessageParser<Unknown2> Parser { get { return _parser; } }

            public static pbr::MessageDescriptor Descriptor {
              get { return global::PokemonGo.RocketAPI.GeneratedCode.FortDetailResponse.Types.Unknown6.Descriptor.NestedTypes[0]; }
            }

            pbr::MessageDescriptor pb::IMessage.Descriptor {
              get { return Descriptor; }
            }

            public Unknown2() {
              OnConstruction();
            }

            partial void OnConstruction();

            public Unknown2(Unknown2 other) : this() {
              unknown1_ = other.unknown1_;
            }

            public Unknown2 Clone() {
              return new Unknown2(this);
            }

            /// <summary>Field number for the "unknown1" field.</summary>
            public const int Unknown1FieldNumber = 1;
            private pb::ByteString unknown1_ = pb::ByteString.Empty;
            public pb::ByteString Unknown1 {
              get { return unknown1_; }
              set {
                unknown1_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
              }
            }

            public override bool Equals(object other) {
              return Equals(other as Unknown2);
            }

            public bool Equals(Unknown2 other) {
              if (ReferenceEquals(other, null)) {
                return false;
              }
              if (ReferenceEquals(other, this)) {
                return true;
              }
              if (Unknown1 != other.Unknown1) return false;
              return true;
            }

            public override int GetHashCode() {
              int hash = 1;
              if (Unknown1.Length != 0) hash ^= Unknown1.GetHashCode();
              return hash;
            }

            public override string ToString() {
              return pb::JsonFormatter.ToDiagnosticString(this);
            }

            public void WriteTo(pb::CodedOutputStream output) {
              if (Unknown1.Length != 0) {
                output.WriteRawTag(10);
                output.WriteBytes(Unknown1);
              }
            }

            public int CalculateSize() {
              int size = 0;
              if (Unknown1.Length != 0) {
                size += 1 + pb::CodedOutputStream.ComputeBytesSize(Unknown1);
              }
              return size;
            }

            public void MergeFrom(Unknown2 other) {
              if (other == null) {
                return;
              }
              if (other.Unknown1.Length != 0) {
                Unknown1 = other.Unknown1;
              }
            }

            public void MergeFrom(pb::CodedInputStream input) {
              uint tag;
              while ((tag = input.ReadTag()) != 0) {
                switch(tag) {
                  default:
                    input.SkipLastField();
                    break;
                  case 10: {
                    Unknown1 = input.ReadBytes();
                    break;
                  }
                }
              }
            }

          }

        }
        #endregion

      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
      public sealed partial class Unknown7 : pb::IMessage<Unknown7> {
        private static readonly pb::MessageParser<Unknown7> _parser = new pb::MessageParser<Unknown7>(() => new Unknown7());
        public static pb::MessageParser<Unknown7> Parser { get { return _parser; } }

        public static pbr::MessageDescriptor Descriptor {
          get { return global::PokemonGo.RocketAPI.GeneratedCode.FortDetailResponse.Descriptor.NestedTypes[1]; }
        }

        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        public Unknown7() {
          OnConstruction();
        }

        partial void OnConstruction();

        public Unknown7(Unknown7 other) : this() {
          unknown71_ = other.unknown71_;
          unknown72_ = other.unknown72_;
          unknown73_ = other.unknown73_;
        }

        public Unknown7 Clone() {
          return new Unknown7(this);
        }

        /// <summary>Field number for the "unknown71" field.</summary>
        public const int Unknown71FieldNumber = 1;
        private pb::ByteString unknown71_ = pb::ByteString.Empty;
        public pb::ByteString Unknown71 {
          get { return unknown71_; }
          set {
            unknown71_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "unknown72" field.</summary>
        public const int Unknown72FieldNumber = 2;
        private long unknown72_;
        public long Unknown72 {
          get { return unknown72_; }
          set {
            unknown72_ = value;
          }
        }

        /// <summary>Field number for the "unknown73" field.</summary>
        public const int Unknown73FieldNumber = 3;
        private pb::ByteString unknown73_ = pb::ByteString.Empty;
        public pb::ByteString Unknown73 {
          get { return unknown73_; }
          set {
            unknown73_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        public override bool Equals(object other) {
          return Equals(other as Unknown7);
        }

        public bool Equals(Unknown7 other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Unknown71 != other.Unknown71) return false;
          if (Unknown72 != other.Unknown72) return false;
          if (Unknown73 != other.Unknown73) return false;
          return true;
        }

        public override int GetHashCode() {
          int hash = 1;
          if (Unknown71.Length != 0) hash ^= Unknown71.GetHashCode();
          if (Unknown72 != 0L) hash ^= Unknown72.GetHashCode();
          if (Unknown73.Length != 0) hash ^= Unknown73.GetHashCode();
          return hash;
        }

        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        public void WriteTo(pb::CodedOutputStream output) {
          if (Unknown71.Length != 0) {
            output.WriteRawTag(10);
            output.WriteBytes(Unknown71);
          }
          if (Unknown72 != 0L) {
            output.WriteRawTag(16);
            output.WriteInt64(Unknown72);
          }
          if (Unknown73.Length != 0) {
            output.WriteRawTag(26);
            output.WriteBytes(Unknown73);
          }
        }

        public int CalculateSize() {
          int size = 0;
          if (Unknown71.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeBytesSize(Unknown71);
          }
          if (Unknown72 != 0L) {
            size += 1 + pb::CodedOutputStream.ComputeInt64Size(Unknown72);
          }
          if (Unknown73.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeBytesSize(Unknown73);
          }
          return size;
        }

        public void MergeFrom(Unknown7 other) {
          if (other == null) {
            return;
          }
          if (other.Unknown71.Length != 0) {
            Unknown71 = other.Unknown71;
          }
          if (other.Unknown72 != 0L) {
            Unknown72 = other.Unknown72;
          }
          if (other.Unknown73.Length != 0) {
            Unknown73 = other.Unknown73;
          }
        }

        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                input.SkipLastField();
                break;
              case 10: {
                Unknown71 = input.ReadBytes();
                break;
              }
              case 16: {
                Unknown72 = input.ReadInt64();
                break;
              }
              case 26: {
                Unknown73 = input.ReadBytes();
                break;
              }
            }
          }
        }

      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
      public sealed partial class Payload : pb::IMessage<Payload> {
        private static readonly pb::MessageParser<Payload> _parser = new pb::MessageParser<Payload>(() => new Payload());
        public static pb::MessageParser<Payload> Parser { get { return _parser; } }

        public static pbr::MessageDescriptor Descriptor {
          get { return global::PokemonGo.RocketAPI.GeneratedCode.FortDetailResponse.Descriptor.NestedTypes[2]; }
        }

        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        public Payload() {
          OnConstruction();
        }

        partial void OnConstruction();

        public Payload(Payload other) : this() {
          id_ = other.id_;
          team_ = other.team_;
          pokemon_ = other.pokemon_;
          name_ = other.name_;
          imageUrl_ = other.imageUrl_;
          fp_ = other.fp_;
          stamina_ = other.stamina_;
          maxStamina_ = other.maxStamina_;
          fortType_ = other.fortType_;
          latitude_ = other.latitude_;
          longitude_ = other.longitude_;
          description_ = other.description_;
          modifier_ = other.modifier_;
        }

        public Payload Clone() {
          return new Payload(this);
        }

        /// <summary>Field number for the "Id" field.</summary>
        public const int IdFieldNumber = 1;
        private string id_ = "";
        public string Id {
          get { return id_; }
          set {
            id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "Team" field.</summary>
        public const int TeamFieldNumber = 2;
        private int team_;
        public int Team {
          get { return team_; }
          set {
            team_ = value;
          }
        }

        /// <summary>Field number for the "Pokemon" field.</summary>
        public const int PokemonFieldNumber = 3;
        private int pokemon_;
        public int Pokemon {
          get { return pokemon_; }
          set {
            pokemon_ = value;
          }
        }

        /// <summary>Field number for the "Name" field.</summary>
        public const int NameFieldNumber = 4;
        private string name_ = "";
        public string Name {
          get { return name_; }
          set {
            name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "ImageUrl" field.</summary>
        public const int ImageUrlFieldNumber = 5;
        private string imageUrl_ = "";
        public string ImageUrl {
          get { return imageUrl_; }
          set {
            imageUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "Fp" field.</summary>
        public const int FpFieldNumber = 6;
        private int fp_;
        public int Fp {
          get { return fp_; }
          set {
            fp_ = value;
          }
        }

        /// <summary>Field number for the "Stamina" field.</summary>
        public const int StaminaFieldNumber = 7;
        private int stamina_;
        public int Stamina {
          get { return stamina_; }
          set {
            stamina_ = value;
          }
        }

        /// <summary>Field number for the "MaxStamina" field.</summary>
        public const int MaxStaminaFieldNumber = 8;
        private int maxStamina_;
        public int MaxStamina {
          get { return maxStamina_; }
          set {
            maxStamina_ = value;
          }
        }

        /// <summary>Field number for the "FortType" field.</summary>
        public const int FortTypeFieldNumber = 9;
        private int fortType_;
        public int FortType {
          get { return fortType_; }
          set {
            fortType_ = value;
          }
        }

        /// <summary>Field number for the "Latitude" field.</summary>
        public const int LatitudeFieldNumber = 10;
        private long latitude_;
        public long Latitude {
          get { return latitude_; }
          set {
            latitude_ = value;
          }
        }

        /// <summary>Field number for the "Longitude" field.</summary>
        public const int LongitudeFieldNumber = 11;
        private long longitude_;
        public long Longitude {
          get { return longitude_; }
          set {
            longitude_ = value;
          }
        }

        /// <summary>Field number for the "Description" field.</summary>
        public const int DescriptionFieldNumber = 12;
        private string description_ = "";
        public string Description {
          get { return description_; }
          set {
            description_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "Modifier" field.</summary>
        public const int ModifierFieldNumber = 13;
        private int modifier_;
        public int Modifier {
          get { return modifier_; }
          set {
            modifier_ = value;
          }
        }

        public override bool Equals(object other) {
          return Equals(other as Payload);
        }

        public bool Equals(Payload other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Id != other.Id) return false;
          if (Team != other.Team) return false;
          if (Pokemon != other.Pokemon) return false;
          if (Name != other.Name) return false;
          if (ImageUrl != other.ImageUrl) return false;
          if (Fp != other.Fp) return false;
          if (Stamina != other.Stamina) return false;
          if (MaxStamina != other.MaxStamina) return false;
          if (FortType != other.FortType) return false;
          if (Latitude != other.Latitude) return false;
          if (Longitude != other.Longitude) return false;
          if (Description != other.Description) return false;
          if (Modifier != other.Modifier) return false;
          return true;
        }

        public override int GetHashCode() {
          int hash = 1;
          if (Id.Length != 0) hash ^= Id.GetHashCode();
          if (Team != 0) hash ^= Team.GetHashCode();
          if (Pokemon != 0) hash ^= Pokemon.GetHashCode();
          if (Name.Length != 0) hash ^= Name.GetHashCode();
          if (ImageUrl.Length != 0) hash ^= ImageUrl.GetHashCode();
          if (Fp != 0) hash ^= Fp.GetHashCode();
          if (Stamina != 0) hash ^= Stamina.GetHashCode();
          if (MaxStamina != 0) hash ^= MaxStamina.GetHashCode();
          if (FortType != 0) hash ^= FortType.GetHashCode();
          if (Latitude != 0L) hash ^= Latitude.GetHashCode();
          if (Longitude != 0L) hash ^= Longitude.GetHashCode();
          if (Description.Length != 0) hash ^= Description.GetHashCode();
          if (Modifier != 0) hash ^= Modifier.GetHashCode();
          return hash;
        }

        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        public void WriteTo(pb::CodedOutputStream output) {
          if (Id.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(Id);
          }
          if (Team != 0) {
            output.WriteRawTag(16);
            output.WriteInt32(Team);
          }
          if (Pokemon != 0) {
            output.WriteRawTag(24);
            output.WriteInt32(Pokemon);
          }
          if (Name.Length != 0) {
            output.WriteRawTag(34);
            output.WriteString(Name);
          }
          if (ImageUrl.Length != 0) {
            output.WriteRawTag(42);
            output.WriteString(ImageUrl);
          }
          if (Fp != 0) {
            output.WriteRawTag(48);
            output.WriteInt32(Fp);
          }
          if (Stamina != 0) {
            output.WriteRawTag(56);
            output.WriteInt32(Stamina);
          }
          if (MaxStamina != 0) {
            output.WriteRawTag(64);
            output.WriteInt32(MaxStamina);
          }
          if (FortType != 0) {
            output.WriteRawTag(72);
            output.WriteInt32(FortType);
          }
          if (Latitude != 0L) {
            output.WriteRawTag(80);
            output.WriteInt64(Latitude);
          }
          if (Longitude != 0L) {
            output.WriteRawTag(88);
            output.WriteInt64(Longitude);
          }
          if (Description.Length != 0) {
            output.WriteRawTag(98);
            output.WriteString(Description);
          }
          if (Modifier != 0) {
            output.WriteRawTag(104);
            output.WriteInt32(Modifier);
          }
        }

        public int CalculateSize() {
          int size = 0;
          if (Id.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
          }
          if (Team != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(Team);
          }
          if (Pokemon != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(Pokemon);
          }
          if (Name.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
          }
          if (ImageUrl.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(ImageUrl);
          }
          if (Fp != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(Fp);
          }
          if (Stamina != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(Stamina);
          }
          if (MaxStamina != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(MaxStamina);
          }
          if (FortType != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(FortType);
          }
          if (Latitude != 0L) {
            size += 1 + pb::CodedOutputStream.ComputeInt64Size(Latitude);
          }
          if (Longitude != 0L) {
            size += 1 + pb::CodedOutputStream.ComputeInt64Size(Longitude);
          }
          if (Description.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Description);
          }
          if (Modifier != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(Modifier);
          }
          return size;
        }

        public void MergeFrom(Payload other) {
          if (other == null) {
            return;
          }
          if (other.Id.Length != 0) {
            Id = other.Id;
          }
          if (other.Team != 0) {
            Team = other.Team;
          }
          if (other.Pokemon != 0) {
            Pokemon = other.Pokemon;
          }
          if (other.Name.Length != 0) {
            Name = other.Name;
          }
          if (other.ImageUrl.Length != 0) {
            ImageUrl = other.ImageUrl;
          }
          if (other.Fp != 0) {
            Fp = other.Fp;
          }
          if (other.Stamina != 0) {
            Stamina = other.Stamina;
          }
          if (other.MaxStamina != 0) {
            MaxStamina = other.MaxStamina;
          }
          if (other.FortType != 0) {
            FortType = other.FortType;
          }
          if (other.Latitude != 0L) {
            Latitude = other.Latitude;
          }
          if (other.Longitude != 0L) {
            Longitude = other.Longitude;
          }
          if (other.Description.Length != 0) {
            Description = other.Description;
          }
          if (other.Modifier != 0) {
            Modifier = other.Modifier;
          }
        }

        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                input.SkipLastField();
                break;
              case 10: {
                Id = input.ReadString();
                break;
              }
              case 16: {
                Team = input.ReadInt32();
                break;
              }
              case 24: {
                Pokemon = input.ReadInt32();
                break;
              }
              case 34: {
                Name = input.ReadString();
                break;
              }
              case 42: {
                ImageUrl = input.ReadString();
                break;
              }
              case 48: {
                Fp = input.ReadInt32();
                break;
              }
              case 56: {
                Stamina = input.ReadInt32();
                break;
              }
              case 64: {
                MaxStamina = input.ReadInt32();
                break;
              }
              case 72: {
                FortType = input.ReadInt32();
                break;
              }
              case 80: {
                Latitude = input.ReadInt64();
                break;
              }
              case 88: {
                Longitude = input.ReadInt64();
                break;
              }
              case 98: {
                Description = input.ReadString();
                break;
              }
              case 104: {
                Modifier = input.ReadInt32();
                break;
              }
            }
          }
        }

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
