// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProfileResponse.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace PokemonGo.RocketAPI.GeneratedCode {

  /// <summary>Holder for reflection information generated from ProfileResponse.proto</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class ProfileResponseReflection {

    #region Descriptor
    /// <summary>File descriptor for ProfileResponse.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProfileResponseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVQcm9maWxlUmVzcG9uc2UucHJvdG8SIVBva2Vtb25Hby5Sb2NrZXRBUEku",
            "R2VuZXJhdGVkQ29kZSLECgoPUHJvZmlsZVJlc3BvbnNlEhAKCHVua25vd24x",
            "GAEgASgFEhAKCHVua25vd24yGAIgASgDEg8KB2FwaV91cmwYAyABKAkSTQoI",
            "dW5rbm93bjYYBiABKAsyOy5Qb2tlbW9uR28uUm9ja2V0QVBJLkdlbmVyYXRl",
            "ZENvZGUuUHJvZmlsZVJlc3BvbnNlLlVua25vd242EkUKBGF1dGgYByABKAsy",
            "Ny5Qb2tlbW9uR28uUm9ja2V0QVBJLkdlbmVyYXRlZENvZGUuUHJvZmlsZVJl",
            "c3BvbnNlLkF1dGgSSwoHcGF5bG9hZBhkIAMoCzI6LlBva2Vtb25Hby5Sb2Nr",
            "ZXRBUEkuR2VuZXJhdGVkQ29kZS5Qcm9maWxlUmVzcG9uc2UuUGF5bG9hZBIU",
            "CgxlcnJvck1lc3NhZ2UYZSABKAkakgEKCFVua25vd242EhAKCHVua25vd24x",
            "GAEgASgFElYKCHVua25vd24yGAIgASgLMkQuUG9rZW1vbkdvLlJvY2tldEFQ",
            "SS5HZW5lcmF0ZWRDb2RlLlByb2ZpbGVSZXNwb25zZS5Vbmtub3duNi5Vbmtu",
            "b3duMhocCghVbmtub3duMhIQCgh1bmtub3duMRgBIAEoDBo/CgRBdXRoEhEK",
            "CXVua25vd243MRgBIAEoDBIRCgl0aW1lc3RhbXAYAiABKAMSEQoJdW5rbm93",
            "bjczGAMgASgMGqwGCgdQYXlsb2FkEhAKCHVua25vd24xGAEgASgFElMKB3By",
            "b2ZpbGUYAiABKAsyQi5Qb2tlbW9uR28uUm9ja2V0QVBJLkdlbmVyYXRlZENv",
            "ZGUuUHJvZmlsZVJlc3BvbnNlLlBheWxvYWQuUHJvZmlsZRIPCgdzZXR0aW5n",
            "GAMgASgMGqgFCgdQcm9maWxlEhUKDWNyZWF0aW9uX3RpbWUYASABKAMSEAoI",
            "dXNlcm5hbWUYAiABKAkSDAoEdGVhbRgFIAEoBRIQCgh0dXRvcmlhbBgHIAEo",
            "DBJgCgZhdmF0YXIYCCABKAsyUC5Qb2tlbW9uR28uUm9ja2V0QVBJLkdlbmVy",
            "YXRlZENvZGUuUHJvZmlsZVJlc3BvbnNlLlBheWxvYWQuUHJvZmlsZS5BdmF0",
            "YXJEZXRhaWxzEhQKDHBva2Vfc3RvcmFnZRgJIAEoBRIUCgxpdGVtX3N0b3Jh",
            "Z2UYCiABKAUSYgoLZGFpbHlfYm9udXMYCyABKAsyTS5Qb2tlbW9uR28uUm9j",
            "a2V0QVBJLkdlbmVyYXRlZENvZGUuUHJvZmlsZVJlc3BvbnNlLlBheWxvYWQu",
            "UHJvZmlsZS5EYWlseUJvbnVzEhEKCXVua25vd24xMhgMIAEoDBIRCgl1bmtu",
            "b3duMTMYDSABKAwSXQoIY3VycmVuY3kYDiADKAsySy5Qb2tlbW9uR28uUm9j",
            "a2V0QVBJLkdlbmVyYXRlZENvZGUuUHJvZmlsZVJlc3BvbnNlLlBheWxvYWQu",
            "UHJvZmlsZS5DdXJyZW5jeRpYCg1BdmF0YXJEZXRhaWxzEhAKCHVua25vd24y",
            "GAIgASgFEhAKCHVua25vd24zGAMgASgFEhAKCHVua25vd245GAkgASgFEhEK",
            "CXVua25vd24xMBgKIAEoBRpZCgpEYWlseUJvbnVzEh4KFk5leHRDb2xsZWN0",
            "VGltZXN0YW1wTXMYASABKAMSKwojTmV4dERlZmVuZGVyQm9udXNDb2xsZWN0",
            "VGltZXN0YW1wTXMYAiABKAMaKAoIQ3VycmVuY3kSDAoEdHlwZRgBIAEoCRIO",
            "CgZhbW91bnQYAiABKAViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::PokemonGo.RocketAPI.GeneratedCode.ProfileResponse), global::PokemonGo.RocketAPI.GeneratedCode.ProfileResponse.Parser, new[]{ "Unknown1", "Unknown2", "ApiUrl", "Unknown6", "Auth", "Payload", "ErrorMessage" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::PokemonGo.RocketAPI.GeneratedCode.ProfileResponse.Types.Unknown6), global::PokemonGo.RocketAPI.GeneratedCode.ProfileResponse.Types.Unknown6.Parser, new[]{ "Unknown1", "Unknown2" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::PokemonGo.RocketAPI.GeneratedCode.ProfileResponse.Types.Unknown6.Types.Unknown2), global::PokemonGo.RocketAPI.GeneratedCode.ProfileResponse.Types.Unknown6.Types.Unknown2.Parser, new[]{ "Unknown1" }, null, null, null)}),
            new pbr::GeneratedClrTypeInfo(typeof(global::PokemonGo.RocketAPI.GeneratedCode.ProfileResponse.Types.Auth), global::PokemonGo.RocketAPI.GeneratedCode.ProfileResponse.Types.Auth.Parser, new[]{ "Unknown71", "Timestamp", "Unknown73" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::PokemonGo.RocketAPI.GeneratedCode.ProfileResponse.Types.Payload), global::PokemonGo.RocketAPI.GeneratedCode.ProfileResponse.Types.Payload.Parser, new[]{ "Unknown1", "Profile", "Setting" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::PokemonGo.RocketAPI.GeneratedCode.ProfileResponse.Types.Payload.Types.Profile), global::PokemonGo.RocketAPI.GeneratedCode.ProfileResponse.Types.Payload.Types.Profile.Parser, new[]{ "CreationTime", "Username", "Team", "Tutorial", "Avatar", "PokeStorage", "ItemStorage", "DailyBonus", "Unknown12", "Unknown13", "Currency" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::PokemonGo.RocketAPI.GeneratedCode.ProfileResponse.Types.Payload.Types.Profile.Types.AvatarDetails), global::PokemonGo.RocketAPI.GeneratedCode.ProfileResponse.Types.Payload.Types.Profile.Types.AvatarDetails.Parser, new[]{ "Unknown2", "Unknown3", "Unknown9", "Unknown10" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::PokemonGo.RocketAPI.GeneratedCode.ProfileResponse.Types.Payload.Types.Profile.Types.DailyBonus), global::PokemonGo.RocketAPI.GeneratedCode.ProfileResponse.Types.Payload.Types.Profile.Types.DailyBonus.Parser, new[]{ "NextCollectTimestampMs", "NextDefenderBonusCollectTimestampMs" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::PokemonGo.RocketAPI.GeneratedCode.ProfileResponse.Types.Payload.Types.Profile.Types.Currency), global::PokemonGo.RocketAPI.GeneratedCode.ProfileResponse.Types.Payload.Types.Profile.Types.Currency.Parser, new[]{ "Type", "Amount" }, null, null, null)})})})
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class ProfileResponse : pb::IMessage<ProfileResponse> {
    private static readonly pb::MessageParser<ProfileResponse> _parser = new pb::MessageParser<ProfileResponse>(() => new ProfileResponse());
    public static pb::MessageParser<ProfileResponse> Parser { get { return _parser; } }

    public static pbr::MessageDescriptor Descriptor {
      get { return global::PokemonGo.RocketAPI.GeneratedCode.ProfileResponseReflection.Descriptor.MessageTypes[0]; }
    }

    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    public ProfileResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    public ProfileResponse(ProfileResponse other) : this() {
      unknown1_ = other.unknown1_;
      unknown2_ = other.unknown2_;
      apiUrl_ = other.apiUrl_;
      Unknown6 = other.unknown6_ != null ? other.Unknown6.Clone() : null;
      Auth = other.auth_ != null ? other.Auth.Clone() : null;
      payload_ = other.payload_.Clone();
      errorMessage_ = other.errorMessage_;
    }

    public ProfileResponse Clone() {
      return new ProfileResponse(this);
    }

    /// <summary>Field number for the "unknown1" field.</summary>
    public const int Unknown1FieldNumber = 1;
    private int unknown1_;
    public int Unknown1 {
      get { return unknown1_; }
      set {
        unknown1_ = value;
      }
    }

    /// <summary>Field number for the "unknown2" field.</summary>
    public const int Unknown2FieldNumber = 2;
    private long unknown2_;
    public long Unknown2 {
      get { return unknown2_; }
      set {
        unknown2_ = value;
      }
    }

    /// <summary>Field number for the "api_url" field.</summary>
    public const int ApiUrlFieldNumber = 3;
    private string apiUrl_ = "";
    public string ApiUrl {
      get { return apiUrl_; }
      set {
        apiUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "unknown6" field.</summary>
    public const int Unknown6FieldNumber = 6;
    private global::PokemonGo.RocketAPI.GeneratedCode.ProfileResponse.Types.Unknown6 unknown6_;
    public global::PokemonGo.RocketAPI.GeneratedCode.ProfileResponse.Types.Unknown6 Unknown6 {
      get { return unknown6_; }
      set {
        unknown6_ = value;
      }
    }

    /// <summary>Field number for the "auth" field.</summary>
    public const int AuthFieldNumber = 7;
    private global::PokemonGo.RocketAPI.GeneratedCode.ProfileResponse.Types.Auth auth_;
    public global::PokemonGo.RocketAPI.GeneratedCode.ProfileResponse.Types.Auth Auth {
      get { return auth_; }
      set {
        auth_ = value;
      }
    }

    /// <summary>Field number for the "payload" field.</summary>
    public const int PayloadFieldNumber = 100;
    private static readonly pb::FieldCodec<global::PokemonGo.RocketAPI.GeneratedCode.ProfileResponse.Types.Payload> _repeated_payload_codec
        = pb::FieldCodec.ForMessage(802, global::PokemonGo.RocketAPI.GeneratedCode.ProfileResponse.Types.Payload.Parser);
    private readonly pbc::RepeatedField<global::PokemonGo.RocketAPI.GeneratedCode.ProfileResponse.Types.Payload> payload_ = new pbc::RepeatedField<global::PokemonGo.RocketAPI.GeneratedCode.ProfileResponse.Types.Payload>();
    public pbc::RepeatedField<global::PokemonGo.RocketAPI.GeneratedCode.ProfileResponse.Types.Payload> Payload {
      get { return payload_; }
    }

    /// <summary>Field number for the "errorMessage" field.</summary>
    public const int ErrorMessageFieldNumber = 101;
    private string errorMessage_ = "";
    /// <summary>
    /// Should be moved to an error-proto file if error is always 101 field
    /// </summary>
    public string ErrorMessage {
      get { return errorMessage_; }
      set {
        errorMessage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    public override bool Equals(object other) {
      return Equals(other as ProfileResponse);
    }

    public bool Equals(ProfileResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Unknown1 != other.Unknown1) return false;
      if (Unknown2 != other.Unknown2) return false;
      if (ApiUrl != other.ApiUrl) return false;
      if (!object.Equals(Unknown6, other.Unknown6)) return false;
      if (!object.Equals(Auth, other.Auth)) return false;
      if(!payload_.Equals(other.payload_)) return false;
      if (ErrorMessage != other.ErrorMessage) return false;
      return true;
    }

    public override int GetHashCode() {
      int hash = 1;
      if (Unknown1 != 0) hash ^= Unknown1.GetHashCode();
      if (Unknown2 != 0L) hash ^= Unknown2.GetHashCode();
      if (ApiUrl.Length != 0) hash ^= ApiUrl.GetHashCode();
      if (unknown6_ != null) hash ^= Unknown6.GetHashCode();
      if (auth_ != null) hash ^= Auth.GetHashCode();
      hash ^= payload_.GetHashCode();
      if (ErrorMessage.Length != 0) hash ^= ErrorMessage.GetHashCode();
      return hash;
    }

    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (Unknown1 != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Unknown1);
      }
      if (Unknown2 != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Unknown2);
      }
      if (ApiUrl.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ApiUrl);
      }
      if (unknown6_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Unknown6);
      }
      if (auth_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(Auth);
      }
      payload_.WriteTo(output, _repeated_payload_codec);
      if (ErrorMessage.Length != 0) {
        output.WriteRawTag(170, 6);
        output.WriteString(ErrorMessage);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (Unknown1 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Unknown1);
      }
      if (Unknown2 != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Unknown2);
      }
      if (ApiUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ApiUrl);
      }
      if (unknown6_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Unknown6);
      }
      if (auth_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Auth);
      }
      size += payload_.CalculateSize(_repeated_payload_codec);
      if (ErrorMessage.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(ErrorMessage);
      }
      return size;
    }

    public void MergeFrom(ProfileResponse other) {
      if (other == null) {
        return;
      }
      if (other.Unknown1 != 0) {
        Unknown1 = other.Unknown1;
      }
      if (other.Unknown2 != 0L) {
        Unknown2 = other.Unknown2;
      }
      if (other.ApiUrl.Length != 0) {
        ApiUrl = other.ApiUrl;
      }
      if (other.unknown6_ != null) {
        if (unknown6_ == null) {
          unknown6_ = new global::PokemonGo.RocketAPI.GeneratedCode.ProfileResponse.Types.Unknown6();
        }
        Unknown6.MergeFrom(other.Unknown6);
      }
      if (other.auth_ != null) {
        if (auth_ == null) {
          auth_ = new global::PokemonGo.RocketAPI.GeneratedCode.ProfileResponse.Types.Auth();
        }
        Auth.MergeFrom(other.Auth);
      }
      payload_.Add(other.payload_);
      if (other.ErrorMessage.Length != 0) {
        ErrorMessage = other.ErrorMessage;
      }
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Unknown1 = input.ReadInt32();
            break;
          }
          case 16: {
            Unknown2 = input.ReadInt64();
            break;
          }
          case 26: {
            ApiUrl = input.ReadString();
            break;
          }
          case 50: {
            if (unknown6_ == null) {
              unknown6_ = new global::PokemonGo.RocketAPI.GeneratedCode.ProfileResponse.Types.Unknown6();
            }
            input.ReadMessage(unknown6_);
            break;
          }
          case 58: {
            if (auth_ == null) {
              auth_ = new global::PokemonGo.RocketAPI.GeneratedCode.ProfileResponse.Types.Auth();
            }
            input.ReadMessage(auth_);
            break;
          }
          case 802: {
            payload_.AddEntriesFrom(input, _repeated_payload_codec);
            break;
          }
          case 810: {
            ErrorMessage = input.ReadString();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the ProfileResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public static partial class Types {
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
      public sealed partial class Unknown6 : pb::IMessage<Unknown6> {
        private static readonly pb::MessageParser<Unknown6> _parser = new pb::MessageParser<Unknown6>(() => new Unknown6());
        public static pb::MessageParser<Unknown6> Parser { get { return _parser; } }

        public static pbr::MessageDescriptor Descriptor {
          get { return global::PokemonGo.RocketAPI.GeneratedCode.ProfileResponse.Descriptor.NestedTypes[0]; }
        }

        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        public Unknown6() {
          OnConstruction();
        }

        partial void OnConstruction();

        public Unknown6(Unknown6 other) : this() {
          unknown1_ = other.unknown1_;
          Unknown2 = other.unknown2_ != null ? other.Unknown2.Clone() : null;
        }

        public Unknown6 Clone() {
          return new Unknown6(this);
        }

        /// <summary>Field number for the "unknown1" field.</summary>
        public const int Unknown1FieldNumber = 1;
        private int unknown1_;
        public int Unknown1 {
          get { return unknown1_; }
          set {
            unknown1_ = value;
          }
        }

        /// <summary>Field number for the "unknown2" field.</summary>
        public const int Unknown2FieldNumber = 2;
        private global::PokemonGo.RocketAPI.GeneratedCode.ProfileResponse.Types.Unknown6.Types.Unknown2 unknown2_;
        public global::PokemonGo.RocketAPI.GeneratedCode.ProfileResponse.Types.Unknown6.Types.Unknown2 Unknown2 {
          get { return unknown2_; }
          set {
            unknown2_ = value;
          }
        }

        public override bool Equals(object other) {
          return Equals(other as Unknown6);
        }

        public bool Equals(Unknown6 other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Unknown1 != other.Unknown1) return false;
          if (!object.Equals(Unknown2, other.Unknown2)) return false;
          return true;
        }

        public override int GetHashCode() {
          int hash = 1;
          if (Unknown1 != 0) hash ^= Unknown1.GetHashCode();
          if (unknown2_ != null) hash ^= Unknown2.GetHashCode();
          return hash;
        }

        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        public void WriteTo(pb::CodedOutputStream output) {
          if (Unknown1 != 0) {
            output.WriteRawTag(8);
            output.WriteInt32(Unknown1);
          }
          if (unknown2_ != null) {
            output.WriteRawTag(18);
            output.WriteMessage(Unknown2);
          }
        }

        public int CalculateSize() {
          int size = 0;
          if (Unknown1 != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(Unknown1);
          }
          if (unknown2_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(Unknown2);
          }
          return size;
        }

        public void MergeFrom(Unknown6 other) {
          if (other == null) {
            return;
          }
          if (other.Unknown1 != 0) {
            Unknown1 = other.Unknown1;
          }
          if (other.unknown2_ != null) {
            if (unknown2_ == null) {
              unknown2_ = new global::PokemonGo.RocketAPI.GeneratedCode.ProfileResponse.Types.Unknown6.Types.Unknown2();
            }
            Unknown2.MergeFrom(other.Unknown2);
          }
        }

        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                input.SkipLastField();
                break;
              case 8: {
                Unknown1 = input.ReadInt32();
                break;
              }
              case 18: {
                if (unknown2_ == null) {
                  unknown2_ = new global::PokemonGo.RocketAPI.GeneratedCode.ProfileResponse.Types.Unknown6.Types.Unknown2();
                }
                input.ReadMessage(unknown2_);
                break;
              }
            }
          }
        }

        #region Nested types
        /// <summary>Container for nested types declared in the Unknown6 message type.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static partial class Types {
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
          public sealed partial class Unknown2 : pb::IMessage<Unknown2> {
            private static readonly pb::MessageParser<Unknown2> _parser = new pb::MessageParser<Unknown2>(() => new Unknown2());
            public static pb::MessageParser<Unknown2> Parser { get { return _parser; } }

            public static pbr::MessageDescriptor Descriptor {
              get { return global::PokemonGo.RocketAPI.GeneratedCode.ProfileResponse.Types.Unknown6.Descriptor.NestedTypes[0]; }
            }

            pbr::MessageDescriptor pb::IMessage.Descriptor {
              get { return Descriptor; }
            }

            public Unknown2() {
              OnConstruction();
            }

            partial void OnConstruction();

            public Unknown2(Unknown2 other) : this() {
              unknown1_ = other.unknown1_;
            }

            public Unknown2 Clone() {
              return new Unknown2(this);
            }

            /// <summary>Field number for the "unknown1" field.</summary>
            public const int Unknown1FieldNumber = 1;
            private pb::ByteString unknown1_ = pb::ByteString.Empty;
            public pb::ByteString Unknown1 {
              get { return unknown1_; }
              set {
                unknown1_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
              }
            }

            public override bool Equals(object other) {
              return Equals(other as Unknown2);
            }

            public bool Equals(Unknown2 other) {
              if (ReferenceEquals(other, null)) {
                return false;
              }
              if (ReferenceEquals(other, this)) {
                return true;
              }
              if (Unknown1 != other.Unknown1) return false;
              return true;
            }

            public override int GetHashCode() {
              int hash = 1;
              if (Unknown1.Length != 0) hash ^= Unknown1.GetHashCode();
              return hash;
            }

            public override string ToString() {
              return pb::JsonFormatter.ToDiagnosticString(this);
            }

            public void WriteTo(pb::CodedOutputStream output) {
              if (Unknown1.Length != 0) {
                output.WriteRawTag(10);
                output.WriteBytes(Unknown1);
              }
            }

            public int CalculateSize() {
              int size = 0;
              if (Unknown1.Length != 0) {
                size += 1 + pb::CodedOutputStream.ComputeBytesSize(Unknown1);
              }
              return size;
            }

            public void MergeFrom(Unknown2 other) {
              if (other == null) {
                return;
              }
              if (other.Unknown1.Length != 0) {
                Unknown1 = other.Unknown1;
              }
            }

            public void MergeFrom(pb::CodedInputStream input) {
              uint tag;
              while ((tag = input.ReadTag()) != 0) {
                switch(tag) {
                  default:
                    input.SkipLastField();
                    break;
                  case 10: {
                    Unknown1 = input.ReadBytes();
                    break;
                  }
                }
              }
            }

          }

        }
        #endregion

      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
      public sealed partial class Auth : pb::IMessage<Auth> {
        private static readonly pb::MessageParser<Auth> _parser = new pb::MessageParser<Auth>(() => new Auth());
        public static pb::MessageParser<Auth> Parser { get { return _parser; } }

        public static pbr::MessageDescriptor Descriptor {
          get { return global::PokemonGo.RocketAPI.GeneratedCode.ProfileResponse.Descriptor.NestedTypes[1]; }
        }

        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        public Auth() {
          OnConstruction();
        }

        partial void OnConstruction();

        public Auth(Auth other) : this() {
          unknown71_ = other.unknown71_;
          timestamp_ = other.timestamp_;
          unknown73_ = other.unknown73_;
        }

        public Auth Clone() {
          return new Auth(this);
        }

        /// <summary>Field number for the "unknown71" field.</summary>
        public const int Unknown71FieldNumber = 1;
        private pb::ByteString unknown71_ = pb::ByteString.Empty;
        public pb::ByteString Unknown71 {
          get { return unknown71_; }
          set {
            unknown71_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "timestamp" field.</summary>
        public const int TimestampFieldNumber = 2;
        private long timestamp_;
        public long Timestamp {
          get { return timestamp_; }
          set {
            timestamp_ = value;
          }
        }

        /// <summary>Field number for the "unknown73" field.</summary>
        public const int Unknown73FieldNumber = 3;
        private pb::ByteString unknown73_ = pb::ByteString.Empty;
        public pb::ByteString Unknown73 {
          get { return unknown73_; }
          set {
            unknown73_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        public override bool Equals(object other) {
          return Equals(other as Auth);
        }

        public bool Equals(Auth other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Unknown71 != other.Unknown71) return false;
          if (Timestamp != other.Timestamp) return false;
          if (Unknown73 != other.Unknown73) return false;
          return true;
        }

        public override int GetHashCode() {
          int hash = 1;
          if (Unknown71.Length != 0) hash ^= Unknown71.GetHashCode();
          if (Timestamp != 0L) hash ^= Timestamp.GetHashCode();
          if (Unknown73.Length != 0) hash ^= Unknown73.GetHashCode();
          return hash;
        }

        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        public void WriteTo(pb::CodedOutputStream output) {
          if (Unknown71.Length != 0) {
            output.WriteRawTag(10);
            output.WriteBytes(Unknown71);
          }
          if (Timestamp != 0L) {
            output.WriteRawTag(16);
            output.WriteInt64(Timestamp);
          }
          if (Unknown73.Length != 0) {
            output.WriteRawTag(26);
            output.WriteBytes(Unknown73);
          }
        }

        public int CalculateSize() {
          int size = 0;
          if (Unknown71.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeBytesSize(Unknown71);
          }
          if (Timestamp != 0L) {
            size += 1 + pb::CodedOutputStream.ComputeInt64Size(Timestamp);
          }
          if (Unknown73.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeBytesSize(Unknown73);
          }
          return size;
        }

        public void MergeFrom(Auth other) {
          if (other == null) {
            return;
          }
          if (other.Unknown71.Length != 0) {
            Unknown71 = other.Unknown71;
          }
          if (other.Timestamp != 0L) {
            Timestamp = other.Timestamp;
          }
          if (other.Unknown73.Length != 0) {
            Unknown73 = other.Unknown73;
          }
        }

        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                input.SkipLastField();
                break;
              case 10: {
                Unknown71 = input.ReadBytes();
                break;
              }
              case 16: {
                Timestamp = input.ReadInt64();
                break;
              }
              case 26: {
                Unknown73 = input.ReadBytes();
                break;
              }
            }
          }
        }

      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
      public sealed partial class Payload : pb::IMessage<Payload> {
        private static readonly pb::MessageParser<Payload> _parser = new pb::MessageParser<Payload>(() => new Payload());
        public static pb::MessageParser<Payload> Parser { get { return _parser; } }

        public static pbr::MessageDescriptor Descriptor {
          get { return global::PokemonGo.RocketAPI.GeneratedCode.ProfileResponse.Descriptor.NestedTypes[2]; }
        }

        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        public Payload() {
          OnConstruction();
        }

        partial void OnConstruction();

        public Payload(Payload other) : this() {
          unknown1_ = other.unknown1_;
          Profile = other.profile_ != null ? other.Profile.Clone() : null;
          setting_ = other.setting_;
        }

        public Payload Clone() {
          return new Payload(this);
        }

        /// <summary>Field number for the "unknown1" field.</summary>
        public const int Unknown1FieldNumber = 1;
        private int unknown1_;
        public int Unknown1 {
          get { return unknown1_; }
          set {
            unknown1_ = value;
          }
        }

        /// <summary>Field number for the "profile" field.</summary>
        public const int ProfileFieldNumber = 2;
        private global::PokemonGo.RocketAPI.GeneratedCode.ProfileResponse.Types.Payload.Types.Profile profile_;
        public global::PokemonGo.RocketAPI.GeneratedCode.ProfileResponse.Types.Payload.Types.Profile Profile {
          get { return profile_; }
          set {
            profile_ = value;
          }
        }

        /// <summary>Field number for the "setting" field.</summary>
        public const int SettingFieldNumber = 3;
        private pb::ByteString setting_ = pb::ByteString.Empty;
        public pb::ByteString Setting {
          get { return setting_; }
          set {
            setting_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        public override bool Equals(object other) {
          return Equals(other as Payload);
        }

        public bool Equals(Payload other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Unknown1 != other.Unknown1) return false;
          if (!object.Equals(Profile, other.Profile)) return false;
          if (Setting != other.Setting) return false;
          return true;
        }

        public override int GetHashCode() {
          int hash = 1;
          if (Unknown1 != 0) hash ^= Unknown1.GetHashCode();
          if (profile_ != null) hash ^= Profile.GetHashCode();
          if (Setting.Length != 0) hash ^= Setting.GetHashCode();
          return hash;
        }

        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        public void WriteTo(pb::CodedOutputStream output) {
          if (Unknown1 != 0) {
            output.WriteRawTag(8);
            output.WriteInt32(Unknown1);
          }
          if (profile_ != null) {
            output.WriteRawTag(18);
            output.WriteMessage(Profile);
          }
          if (Setting.Length != 0) {
            output.WriteRawTag(26);
            output.WriteBytes(Setting);
          }
        }

        public int CalculateSize() {
          int size = 0;
          if (Unknown1 != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(Unknown1);
          }
          if (profile_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(Profile);
          }
          if (Setting.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeBytesSize(Setting);
          }
          return size;
        }

        public void MergeFrom(Payload other) {
          if (other == null) {
            return;
          }
          if (other.Unknown1 != 0) {
            Unknown1 = other.Unknown1;
          }
          if (other.profile_ != null) {
            if (profile_ == null) {
              profile_ = new global::PokemonGo.RocketAPI.GeneratedCode.ProfileResponse.Types.Payload.Types.Profile();
            }
            Profile.MergeFrom(other.Profile);
          }
          if (other.Setting.Length != 0) {
            Setting = other.Setting;
          }
        }

        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                input.SkipLastField();
                break;
              case 8: {
                Unknown1 = input.ReadInt32();
                break;
              }
              case 18: {
                if (profile_ == null) {
                  profile_ = new global::PokemonGo.RocketAPI.GeneratedCode.ProfileResponse.Types.Payload.Types.Profile();
                }
                input.ReadMessage(profile_);
                break;
              }
              case 26: {
                Setting = input.ReadBytes();
                break;
              }
            }
          }
        }

        #region Nested types
        /// <summary>Container for nested types declared in the Payload message type.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static partial class Types {
          [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
          public sealed partial class Profile : pb::IMessage<Profile> {
            private static readonly pb::MessageParser<Profile> _parser = new pb::MessageParser<Profile>(() => new Profile());
            public static pb::MessageParser<Profile> Parser { get { return _parser; } }

            public static pbr::MessageDescriptor Descriptor {
              get { return global::PokemonGo.RocketAPI.GeneratedCode.ProfileResponse.Types.Payload.Descriptor.NestedTypes[0]; }
            }

            pbr::MessageDescriptor pb::IMessage.Descriptor {
              get { return Descriptor; }
            }

            public Profile() {
              OnConstruction();
            }

            partial void OnConstruction();

            public Profile(Profile other) : this() {
              creationTime_ = other.creationTime_;
              username_ = other.username_;
              team_ = other.team_;
              tutorial_ = other.tutorial_;
              Avatar = other.avatar_ != null ? other.Avatar.Clone() : null;
              pokeStorage_ = other.pokeStorage_;
              itemStorage_ = other.itemStorage_;
              DailyBonus = other.dailyBonus_ != null ? other.DailyBonus.Clone() : null;
              unknown12_ = other.unknown12_;
              unknown13_ = other.unknown13_;
              currency_ = other.currency_.Clone();
            }

            public Profile Clone() {
              return new Profile(this);
            }

            /// <summary>Field number for the "creation_time" field.</summary>
            public const int CreationTimeFieldNumber = 1;
            private long creationTime_;
            public long CreationTime {
              get { return creationTime_; }
              set {
                creationTime_ = value;
              }
            }

            /// <summary>Field number for the "username" field.</summary>
            public const int UsernameFieldNumber = 2;
            private string username_ = "";
            public string Username {
              get { return username_; }
              set {
                username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
              }
            }

            /// <summary>Field number for the "team" field.</summary>
            public const int TeamFieldNumber = 5;
            private int team_;
            public int Team {
              get { return team_; }
              set {
                team_ = value;
              }
            }

            /// <summary>Field number for the "tutorial" field.</summary>
            public const int TutorialFieldNumber = 7;
            private pb::ByteString tutorial_ = pb::ByteString.Empty;
            public pb::ByteString Tutorial {
              get { return tutorial_; }
              set {
                tutorial_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
              }
            }

            /// <summary>Field number for the "avatar" field.</summary>
            public const int AvatarFieldNumber = 8;
            private global::PokemonGo.RocketAPI.GeneratedCode.ProfileResponse.Types.Payload.Types.Profile.Types.AvatarDetails avatar_;
            public global::PokemonGo.RocketAPI.GeneratedCode.ProfileResponse.Types.Payload.Types.Profile.Types.AvatarDetails Avatar {
              get { return avatar_; }
              set {
                avatar_ = value;
              }
            }

            /// <summary>Field number for the "poke_storage" field.</summary>
            public const int PokeStorageFieldNumber = 9;
            private int pokeStorage_;
            public int PokeStorage {
              get { return pokeStorage_; }
              set {
                pokeStorage_ = value;
              }
            }

            /// <summary>Field number for the "item_storage" field.</summary>
            public const int ItemStorageFieldNumber = 10;
            private int itemStorage_;
            public int ItemStorage {
              get { return itemStorage_; }
              set {
                itemStorage_ = value;
              }
            }

            /// <summary>Field number for the "daily_bonus" field.</summary>
            public const int DailyBonusFieldNumber = 11;
            private global::PokemonGo.RocketAPI.GeneratedCode.ProfileResponse.Types.Payload.Types.Profile.Types.DailyBonus dailyBonus_;
            public global::PokemonGo.RocketAPI.GeneratedCode.ProfileResponse.Types.Payload.Types.Profile.Types.DailyBonus DailyBonus {
              get { return dailyBonus_; }
              set {
                dailyBonus_ = value;
              }
            }

            /// <summary>Field number for the "unknown12" field.</summary>
            public const int Unknown12FieldNumber = 12;
            private pb::ByteString unknown12_ = pb::ByteString.Empty;
            public pb::ByteString Unknown12 {
              get { return unknown12_; }
              set {
                unknown12_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
              }
            }

            /// <summary>Field number for the "unknown13" field.</summary>
            public const int Unknown13FieldNumber = 13;
            private pb::ByteString unknown13_ = pb::ByteString.Empty;
            public pb::ByteString Unknown13 {
              get { return unknown13_; }
              set {
                unknown13_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
              }
            }

            /// <summary>Field number for the "currency" field.</summary>
            public const int CurrencyFieldNumber = 14;
            private static readonly pb::FieldCodec<global::PokemonGo.RocketAPI.GeneratedCode.ProfileResponse.Types.Payload.Types.Profile.Types.Currency> _repeated_currency_codec
                = pb::FieldCodec.ForMessage(114, global::PokemonGo.RocketAPI.GeneratedCode.ProfileResponse.Types.Payload.Types.Profile.Types.Currency.Parser);
            private readonly pbc::RepeatedField<global::PokemonGo.RocketAPI.GeneratedCode.ProfileResponse.Types.Payload.Types.Profile.Types.Currency> currency_ = new pbc::RepeatedField<global::PokemonGo.RocketAPI.GeneratedCode.ProfileResponse.Types.Payload.Types.Profile.Types.Currency>();
            public pbc::RepeatedField<global::PokemonGo.RocketAPI.GeneratedCode.ProfileResponse.Types.Payload.Types.Profile.Types.Currency> Currency {
              get { return currency_; }
            }

            public override bool Equals(object other) {
              return Equals(other as Profile);
            }

            public bool Equals(Profile other) {
              if (ReferenceEquals(other, null)) {
                return false;
              }
              if (ReferenceEquals(other, this)) {
                return true;
              }
              if (CreationTime != other.CreationTime) return false;
              if (Username != other.Username) return false;
              if (Team != other.Team) return false;
              if (Tutorial != other.Tutorial) return false;
              if (!object.Equals(Avatar, other.Avatar)) return false;
              if (PokeStorage != other.PokeStorage) return false;
              if (ItemStorage != other.ItemStorage) return false;
              if (!object.Equals(DailyBonus, other.DailyBonus)) return false;
              if (Unknown12 != other.Unknown12) return false;
              if (Unknown13 != other.Unknown13) return false;
              if(!currency_.Equals(other.currency_)) return false;
              return true;
            }

            public override int GetHashCode() {
              int hash = 1;
              if (CreationTime != 0L) hash ^= CreationTime.GetHashCode();
              if (Username.Length != 0) hash ^= Username.GetHashCode();
              if (Team != 0) hash ^= Team.GetHashCode();
              if (Tutorial.Length != 0) hash ^= Tutorial.GetHashCode();
              if (avatar_ != null) hash ^= Avatar.GetHashCode();
              if (PokeStorage != 0) hash ^= PokeStorage.GetHashCode();
              if (ItemStorage != 0) hash ^= ItemStorage.GetHashCode();
              if (dailyBonus_ != null) hash ^= DailyBonus.GetHashCode();
              if (Unknown12.Length != 0) hash ^= Unknown12.GetHashCode();
              if (Unknown13.Length != 0) hash ^= Unknown13.GetHashCode();
              hash ^= currency_.GetHashCode();
              return hash;
            }

            public override string ToString() {
              return pb::JsonFormatter.ToDiagnosticString(this);
            }

            public void WriteTo(pb::CodedOutputStream output) {
              if (CreationTime != 0L) {
                output.WriteRawTag(8);
                output.WriteInt64(CreationTime);
              }
              if (Username.Length != 0) {
                output.WriteRawTag(18);
                output.WriteString(Username);
              }
              if (Team != 0) {
                output.WriteRawTag(40);
                output.WriteInt32(Team);
              }
              if (Tutorial.Length != 0) {
                output.WriteRawTag(58);
                output.WriteBytes(Tutorial);
              }
              if (avatar_ != null) {
                output.WriteRawTag(66);
                output.WriteMessage(Avatar);
              }
              if (PokeStorage != 0) {
                output.WriteRawTag(72);
                output.WriteInt32(PokeStorage);
              }
              if (ItemStorage != 0) {
                output.WriteRawTag(80);
                output.WriteInt32(ItemStorage);
              }
              if (dailyBonus_ != null) {
                output.WriteRawTag(90);
                output.WriteMessage(DailyBonus);
              }
              if (Unknown12.Length != 0) {
                output.WriteRawTag(98);
                output.WriteBytes(Unknown12);
              }
              if (Unknown13.Length != 0) {
                output.WriteRawTag(106);
                output.WriteBytes(Unknown13);
              }
              currency_.WriteTo(output, _repeated_currency_codec);
            }

            public int CalculateSize() {
              int size = 0;
              if (CreationTime != 0L) {
                size += 1 + pb::CodedOutputStream.ComputeInt64Size(CreationTime);
              }
              if (Username.Length != 0) {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
              }
              if (Team != 0) {
                size += 1 + pb::CodedOutputStream.ComputeInt32Size(Team);
              }
              if (Tutorial.Length != 0) {
                size += 1 + pb::CodedOutputStream.ComputeBytesSize(Tutorial);
              }
              if (avatar_ != null) {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(Avatar);
              }
              if (PokeStorage != 0) {
                size += 1 + pb::CodedOutputStream.ComputeInt32Size(PokeStorage);
              }
              if (ItemStorage != 0) {
                size += 1 + pb::CodedOutputStream.ComputeInt32Size(ItemStorage);
              }
              if (dailyBonus_ != null) {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(DailyBonus);
              }
              if (Unknown12.Length != 0) {
                size += 1 + pb::CodedOutputStream.ComputeBytesSize(Unknown12);
              }
              if (Unknown13.Length != 0) {
                size += 1 + pb::CodedOutputStream.ComputeBytesSize(Unknown13);
              }
              size += currency_.CalculateSize(_repeated_currency_codec);
              return size;
            }

            public void MergeFrom(Profile other) {
              if (other == null) {
                return;
              }
              if (other.CreationTime != 0L) {
                CreationTime = other.CreationTime;
              }
              if (other.Username.Length != 0) {
                Username = other.Username;
              }
              if (other.Team != 0) {
                Team = other.Team;
              }
              if (other.Tutorial.Length != 0) {
                Tutorial = other.Tutorial;
              }
              if (other.avatar_ != null) {
                if (avatar_ == null) {
                  avatar_ = new global::PokemonGo.RocketAPI.GeneratedCode.ProfileResponse.Types.Payload.Types.Profile.Types.AvatarDetails();
                }
                Avatar.MergeFrom(other.Avatar);
              }
              if (other.PokeStorage != 0) {
                PokeStorage = other.PokeStorage;
              }
              if (other.ItemStorage != 0) {
                ItemStorage = other.ItemStorage;
              }
              if (other.dailyBonus_ != null) {
                if (dailyBonus_ == null) {
                  dailyBonus_ = new global::PokemonGo.RocketAPI.GeneratedCode.ProfileResponse.Types.Payload.Types.Profile.Types.DailyBonus();
                }
                DailyBonus.MergeFrom(other.DailyBonus);
              }
              if (other.Unknown12.Length != 0) {
                Unknown12 = other.Unknown12;
              }
              if (other.Unknown13.Length != 0) {
                Unknown13 = other.Unknown13;
              }
              currency_.Add(other.currency_);
            }

            public void MergeFrom(pb::CodedInputStream input) {
              uint tag;
              while ((tag = input.ReadTag()) != 0) {
                switch(tag) {
                  default:
                    input.SkipLastField();
                    break;
                  case 8: {
                    CreationTime = input.ReadInt64();
                    break;
                  }
                  case 18: {
                    Username = input.ReadString();
                    break;
                  }
                  case 40: {
                    Team = input.ReadInt32();
                    break;
                  }
                  case 58: {
                    Tutorial = input.ReadBytes();
                    break;
                  }
                  case 66: {
                    if (avatar_ == null) {
                      avatar_ = new global::PokemonGo.RocketAPI.GeneratedCode.ProfileResponse.Types.Payload.Types.Profile.Types.AvatarDetails();
                    }
                    input.ReadMessage(avatar_);
                    break;
                  }
                  case 72: {
                    PokeStorage = input.ReadInt32();
                    break;
                  }
                  case 80: {
                    ItemStorage = input.ReadInt32();
                    break;
                  }
                  case 90: {
                    if (dailyBonus_ == null) {
                      dailyBonus_ = new global::PokemonGo.RocketAPI.GeneratedCode.ProfileResponse.Types.Payload.Types.Profile.Types.DailyBonus();
                    }
                    input.ReadMessage(dailyBonus_);
                    break;
                  }
                  case 98: {
                    Unknown12 = input.ReadBytes();
                    break;
                  }
                  case 106: {
                    Unknown13 = input.ReadBytes();
                    break;
                  }
                  case 114: {
                    currency_.AddEntriesFrom(input, _repeated_currency_codec);
                    break;
                  }
                }
              }
            }

            #region Nested types
            /// <summary>Container for nested types declared in the Profile message type.</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static partial class Types {
              [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
              public sealed partial class AvatarDetails : pb::IMessage<AvatarDetails> {
                private static readonly pb::MessageParser<AvatarDetails> _parser = new pb::MessageParser<AvatarDetails>(() => new AvatarDetails());
                public static pb::MessageParser<AvatarDetails> Parser { get { return _parser; } }

                public static pbr::MessageDescriptor Descriptor {
                  get { return global::PokemonGo.RocketAPI.GeneratedCode.ProfileResponse.Types.Payload.Types.Profile.Descriptor.NestedTypes[0]; }
                }

                pbr::MessageDescriptor pb::IMessage.Descriptor {
                  get { return Descriptor; }
                }

                public AvatarDetails() {
                  OnConstruction();
                }

                partial void OnConstruction();

                public AvatarDetails(AvatarDetails other) : this() {
                  unknown2_ = other.unknown2_;
                  unknown3_ = other.unknown3_;
                  unknown9_ = other.unknown9_;
                  unknown10_ = other.unknown10_;
                }

                public AvatarDetails Clone() {
                  return new AvatarDetails(this);
                }

                /// <summary>Field number for the "unknown2" field.</summary>
                public const int Unknown2FieldNumber = 2;
                private int unknown2_;
                public int Unknown2 {
                  get { return unknown2_; }
                  set {
                    unknown2_ = value;
                  }
                }

                /// <summary>Field number for the "unknown3" field.</summary>
                public const int Unknown3FieldNumber = 3;
                private int unknown3_;
                public int Unknown3 {
                  get { return unknown3_; }
                  set {
                    unknown3_ = value;
                  }
                }

                /// <summary>Field number for the "unknown9" field.</summary>
                public const int Unknown9FieldNumber = 9;
                private int unknown9_;
                public int Unknown9 {
                  get { return unknown9_; }
                  set {
                    unknown9_ = value;
                  }
                }

                /// <summary>Field number for the "unknown10" field.</summary>
                public const int Unknown10FieldNumber = 10;
                private int unknown10_;
                public int Unknown10 {
                  get { return unknown10_; }
                  set {
                    unknown10_ = value;
                  }
                }

                public override bool Equals(object other) {
                  return Equals(other as AvatarDetails);
                }

                public bool Equals(AvatarDetails other) {
                  if (ReferenceEquals(other, null)) {
                    return false;
                  }
                  if (ReferenceEquals(other, this)) {
                    return true;
                  }
                  if (Unknown2 != other.Unknown2) return false;
                  if (Unknown3 != other.Unknown3) return false;
                  if (Unknown9 != other.Unknown9) return false;
                  if (Unknown10 != other.Unknown10) return false;
                  return true;
                }

                public override int GetHashCode() {
                  int hash = 1;
                  if (Unknown2 != 0) hash ^= Unknown2.GetHashCode();
                  if (Unknown3 != 0) hash ^= Unknown3.GetHashCode();
                  if (Unknown9 != 0) hash ^= Unknown9.GetHashCode();
                  if (Unknown10 != 0) hash ^= Unknown10.GetHashCode();
                  return hash;
                }

                public override string ToString() {
                  return pb::JsonFormatter.ToDiagnosticString(this);
                }

                public void WriteTo(pb::CodedOutputStream output) {
                  if (Unknown2 != 0) {
                    output.WriteRawTag(16);
                    output.WriteInt32(Unknown2);
                  }
                  if (Unknown3 != 0) {
                    output.WriteRawTag(24);
                    output.WriteInt32(Unknown3);
                  }
                  if (Unknown9 != 0) {
                    output.WriteRawTag(72);
                    output.WriteInt32(Unknown9);
                  }
                  if (Unknown10 != 0) {
                    output.WriteRawTag(80);
                    output.WriteInt32(Unknown10);
                  }
                }

                public int CalculateSize() {
                  int size = 0;
                  if (Unknown2 != 0) {
                    size += 1 + pb::CodedOutputStream.ComputeInt32Size(Unknown2);
                  }
                  if (Unknown3 != 0) {
                    size += 1 + pb::CodedOutputStream.ComputeInt32Size(Unknown3);
                  }
                  if (Unknown9 != 0) {
                    size += 1 + pb::CodedOutputStream.ComputeInt32Size(Unknown9);
                  }
                  if (Unknown10 != 0) {
                    size += 1 + pb::CodedOutputStream.ComputeInt32Size(Unknown10);
                  }
                  return size;
                }

                public void MergeFrom(AvatarDetails other) {
                  if (other == null) {
                    return;
                  }
                  if (other.Unknown2 != 0) {
                    Unknown2 = other.Unknown2;
                  }
                  if (other.Unknown3 != 0) {
                    Unknown3 = other.Unknown3;
                  }
                  if (other.Unknown9 != 0) {
                    Unknown9 = other.Unknown9;
                  }
                  if (other.Unknown10 != 0) {
                    Unknown10 = other.Unknown10;
                  }
                }

                public void MergeFrom(pb::CodedInputStream input) {
                  uint tag;
                  while ((tag = input.ReadTag()) != 0) {
                    switch(tag) {
                      default:
                        input.SkipLastField();
                        break;
                      case 16: {
                        Unknown2 = input.ReadInt32();
                        break;
                      }
                      case 24: {
                        Unknown3 = input.ReadInt32();
                        break;
                      }
                      case 72: {
                        Unknown9 = input.ReadInt32();
                        break;
                      }
                      case 80: {
                        Unknown10 = input.ReadInt32();
                        break;
                      }
                    }
                  }
                }

              }

              [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
              public sealed partial class DailyBonus : pb::IMessage<DailyBonus> {
                private static readonly pb::MessageParser<DailyBonus> _parser = new pb::MessageParser<DailyBonus>(() => new DailyBonus());
                public static pb::MessageParser<DailyBonus> Parser { get { return _parser; } }

                public static pbr::MessageDescriptor Descriptor {
                  get { return global::PokemonGo.RocketAPI.GeneratedCode.ProfileResponse.Types.Payload.Types.Profile.Descriptor.NestedTypes[1]; }
                }

                pbr::MessageDescriptor pb::IMessage.Descriptor {
                  get { return Descriptor; }
                }

                public DailyBonus() {
                  OnConstruction();
                }

                partial void OnConstruction();

                public DailyBonus(DailyBonus other) : this() {
                  nextCollectTimestampMs_ = other.nextCollectTimestampMs_;
                  nextDefenderBonusCollectTimestampMs_ = other.nextDefenderBonusCollectTimestampMs_;
                }

                public DailyBonus Clone() {
                  return new DailyBonus(this);
                }

                /// <summary>Field number for the "NextCollectTimestampMs" field.</summary>
                public const int NextCollectTimestampMsFieldNumber = 1;
                private long nextCollectTimestampMs_;
                public long NextCollectTimestampMs {
                  get { return nextCollectTimestampMs_; }
                  set {
                    nextCollectTimestampMs_ = value;
                  }
                }

                /// <summary>Field number for the "NextDefenderBonusCollectTimestampMs" field.</summary>
                public const int NextDefenderBonusCollectTimestampMsFieldNumber = 2;
                private long nextDefenderBonusCollectTimestampMs_;
                public long NextDefenderBonusCollectTimestampMs {
                  get { return nextDefenderBonusCollectTimestampMs_; }
                  set {
                    nextDefenderBonusCollectTimestampMs_ = value;
                  }
                }

                public override bool Equals(object other) {
                  return Equals(other as DailyBonus);
                }

                public bool Equals(DailyBonus other) {
                  if (ReferenceEquals(other, null)) {
                    return false;
                  }
                  if (ReferenceEquals(other, this)) {
                    return true;
                  }
                  if (NextCollectTimestampMs != other.NextCollectTimestampMs) return false;
                  if (NextDefenderBonusCollectTimestampMs != other.NextDefenderBonusCollectTimestampMs) return false;
                  return true;
                }

                public override int GetHashCode() {
                  int hash = 1;
                  if (NextCollectTimestampMs != 0L) hash ^= NextCollectTimestampMs.GetHashCode();
                  if (NextDefenderBonusCollectTimestampMs != 0L) hash ^= NextDefenderBonusCollectTimestampMs.GetHashCode();
                  return hash;
                }

                public override string ToString() {
                  return pb::JsonFormatter.ToDiagnosticString(this);
                }

                public void WriteTo(pb::CodedOutputStream output) {
                  if (NextCollectTimestampMs != 0L) {
                    output.WriteRawTag(8);
                    output.WriteInt64(NextCollectTimestampMs);
                  }
                  if (NextDefenderBonusCollectTimestampMs != 0L) {
                    output.WriteRawTag(16);
                    output.WriteInt64(NextDefenderBonusCollectTimestampMs);
                  }
                }

                public int CalculateSize() {
                  int size = 0;
                  if (NextCollectTimestampMs != 0L) {
                    size += 1 + pb::CodedOutputStream.ComputeInt64Size(NextCollectTimestampMs);
                  }
                  if (NextDefenderBonusCollectTimestampMs != 0L) {
                    size += 1 + pb::CodedOutputStream.ComputeInt64Size(NextDefenderBonusCollectTimestampMs);
                  }
                  return size;
                }

                public void MergeFrom(DailyBonus other) {
                  if (other == null) {
                    return;
                  }
                  if (other.NextCollectTimestampMs != 0L) {
                    NextCollectTimestampMs = other.NextCollectTimestampMs;
                  }
                  if (other.NextDefenderBonusCollectTimestampMs != 0L) {
                    NextDefenderBonusCollectTimestampMs = other.NextDefenderBonusCollectTimestampMs;
                  }
                }

                public void MergeFrom(pb::CodedInputStream input) {
                  uint tag;
                  while ((tag = input.ReadTag()) != 0) {
                    switch(tag) {
                      default:
                        input.SkipLastField();
                        break;
                      case 8: {
                        NextCollectTimestampMs = input.ReadInt64();
                        break;
                      }
                      case 16: {
                        NextDefenderBonusCollectTimestampMs = input.ReadInt64();
                        break;
                      }
                    }
                  }
                }

              }

              [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
              public sealed partial class Currency : pb::IMessage<Currency> {
                private static readonly pb::MessageParser<Currency> _parser = new pb::MessageParser<Currency>(() => new Currency());
                public static pb::MessageParser<Currency> Parser { get { return _parser; } }

                public static pbr::MessageDescriptor Descriptor {
                  get { return global::PokemonGo.RocketAPI.GeneratedCode.ProfileResponse.Types.Payload.Types.Profile.Descriptor.NestedTypes[2]; }
                }

                pbr::MessageDescriptor pb::IMessage.Descriptor {
                  get { return Descriptor; }
                }

                public Currency() {
                  OnConstruction();
                }

                partial void OnConstruction();

                public Currency(Currency other) : this() {
                  type_ = other.type_;
                  amount_ = other.amount_;
                }

                public Currency Clone() {
                  return new Currency(this);
                }

                /// <summary>Field number for the "type" field.</summary>
                public const int TypeFieldNumber = 1;
                private string type_ = "";
                public string Type {
                  get { return type_; }
                  set {
                    type_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
                  }
                }

                /// <summary>Field number for the "amount" field.</summary>
                public const int AmountFieldNumber = 2;
                private int amount_;
                public int Amount {
                  get { return amount_; }
                  set {
                    amount_ = value;
                  }
                }

                public override bool Equals(object other) {
                  return Equals(other as Currency);
                }

                public bool Equals(Currency other) {
                  if (ReferenceEquals(other, null)) {
                    return false;
                  }
                  if (ReferenceEquals(other, this)) {
                    return true;
                  }
                  if (Type != other.Type) return false;
                  if (Amount != other.Amount) return false;
                  return true;
                }

                public override int GetHashCode() {
                  int hash = 1;
                  if (Type.Length != 0) hash ^= Type.GetHashCode();
                  if (Amount != 0) hash ^= Amount.GetHashCode();
                  return hash;
                }

                public override string ToString() {
                  return pb::JsonFormatter.ToDiagnosticString(this);
                }

                public void WriteTo(pb::CodedOutputStream output) {
                  if (Type.Length != 0) {
                    output.WriteRawTag(10);
                    output.WriteString(Type);
                  }
                  if (Amount != 0) {
                    output.WriteRawTag(16);
                    output.WriteInt32(Amount);
                  }
                }

                public int CalculateSize() {
                  int size = 0;
                  if (Type.Length != 0) {
                    size += 1 + pb::CodedOutputStream.ComputeStringSize(Type);
                  }
                  if (Amount != 0) {
                    size += 1 + pb::CodedOutputStream.ComputeInt32Size(Amount);
                  }
                  return size;
                }

                public void MergeFrom(Currency other) {
                  if (other == null) {
                    return;
                  }
                  if (other.Type.Length != 0) {
                    Type = other.Type;
                  }
                  if (other.Amount != 0) {
                    Amount = other.Amount;
                  }
                }

                public void MergeFrom(pb::CodedInputStream input) {
                  uint tag;
                  while ((tag = input.ReadTag()) != 0) {
                    switch(tag) {
                      default:
                        input.SkipLastField();
                        break;
                      case 10: {
                        Type = input.ReadString();
                        break;
                      }
                      case 16: {
                        Amount = input.ReadInt32();
                        break;
                      }
                    }
                  }
                }

              }

            }
            #endregion

          }

        }
        #endregion

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
